### ISSUE TITLE
Updated documentation for allowed locales

### ISSUE THREAD

**Issue by fleawig** [SketchUp/api-issue-tracker#116]
1. SketchUp 2018 and earlier
2. All platforms

This issue follows from this discussion in the Developers forum: [https://forums.sketchup.com/t/programmatically-get-list-of-allowed-locales/75803/3](https://forums.sketchup.com/t/programmatically-get-list-of-allowed-locales/75803/3)

A current list of allowed locale codes is provided under the #get_locale method, but the list is outdated. For example, Swedish (sv) is now supported, but not documented there. 

It was suggested that it would be good to have documentation specifying the allowed values for various versions.

The initial question concerned getting a list of supported locale codes programmatically, but respondents felt this was unlikely to be implemented. I'm just mentioning it here because, well, you never know...

**Comment by DanRathbun** [comment]
I'd suggest just an array referenced by a constant within the `Sketchup::RegionalSettings` module.

When something like this gets implemented as a method that returns an array, it has often in the past been attached to a weird place in the API.

Ex: [`Sketchup::Model.list_datums`](http://ruby.sketchup.com/Sketchup/Model.html#list_datums-instance_method)

We'd first go looking for this in the [`UTM`](http://ruby.sketchup.com/Geom/UTM.html) class, and not finding it, we secondly check the Geom module.

Anyway, I think it less expensive to have a simple constant (`SUPPORTED_LOCALES`) referencing an array then a method. It could be in the `Sketchup` module if you felt it wasn't actual a regional "setting".

----

In the past, (because this kind of thing is so low priority,) these kind of enumerations have been created by the plugin developers and shared around.
Enumerations for virtual key IDs, send_action integers, Tool IDs, etc. come to mind.

~

**Comment by Eneroth3** [comment]
I'm not sure the API should have a method that programmatically lists supported languages, at least not the way languages work now. If I understand it correctly, any language could in theory be installed at any time to SketchUp by having its files placed in the resource folder. I don't think SketchUp has a list internally of what languages are "valid".

I think it makes the most sense here to list _examples_ of locales, not try to define them, and reference the download page for the up to date list.

**Comment by DanRathbun** [comment]
There actually are quite a few places in the API that have methods returning "valid" member for keys used as arguments to setter methods. This allows for some validation between getting a key from the user and applying it.

So the "test" **might** be, ... Is there an API application setter method that takes a locale String argument ?

(Playing advocate): There might be some that say that the executable itself can take this argument, and Ruby code might be making a call to start another SU instance in another locale language, or creating a desktop shortcut that does this.

----

Again, as said, coders have historically created their own enumerations. When things change, the coders update their code to add members to the enumeration.

Sure it might be nice to have this, but it would always be left at the bottom of the priority list, and never percolate to the top.

I do agree with the OP, in that the API docs explicitly state "_Valid members are_ ..." which might need to change to "_Examples are ..._".

And **perhaps** add a note that more languages might be added at any time ?

**Comment by DanRathbun** [comment]
So this was also labeled as an **enhancement**. But none was done, only the doc clarifications.

Should this be reopened for enhancement ? ... or should it be labeled "will not/cannot enhance" ?

**Comment by thomthom** [comment]
This was addressing the original post, the out of date documentation. Don't recall why I added "enhancement". But you had some other suggestions deeper in this thread; feel free to open a new ticket for those.

**Comment by DanRathbun** [comment]
>  Don't recall why I added "enhancement". 

Well you [said](https://github.com/SketchUp/api-issue-tracker/issues/116#issuecomment-417267471) ...
> _I did mark this issue as a feature request as well - so we have it for consideration._

... and because we and the OP suggested that, like other enumerations, there are API getter methods that return and array of allowable string names. But Julia and yourself pointed out that the set of allowable languages is likely to change too often and is a feature of the installer build.

So it was never decided one way of the other.

The doc **was** changed from "allowed" to "examples" per comments (above,) but this was not what this issue thread was requesting.

----

I personally am against opening another issue thread, when all the discussion about such a feature is here in **this** thread.

If it is not possible, or likely that such a method would ever be implemented mark it so, and we'll let it die.

A coder could always use the [`Dir`](https://ruby-doc.org/core-2.7.1/Dir.html) class to "sniff" out what the machine's language subfolders are in the SketchUp "Resources" folder. (Ie, what languages were actually installed for use with SketchUp.)

Another point, the OP logged this for "SU2018 and older", which cannot by policy be updated anyway.

**Comment by thomthom** [comment]
I'm leaving this closed as a doc issues. These other feature requests deserve more specific feature request issues as the discussion here as rather general.
