### ISSUE TITLE
Sketchup crashes when printing hash from Ruby console

### ISSUE THREAD

**Issue by cedarmora** [SketchUp/api-issue-tracker#122]
Please include the following:

1. SketchUp/LayOut Version: Sketchup 2017
2. OS Platform: Windows 10

Describe briefly what you are doing and what is happening.

Attempting to print hash from ruby console. It crashes Sketchup or throws an error.

Describe what the expected result is.

It prints the hash to the console.

```ruby
# Complete reprodusible code snippet. (Important!)

line = {"id"=>"12", "name"=>"Overhead Doors", "repeat"=>true, "taxed"=>true, "crew"=>["building"], "fieldSuffixes"=>["overhead_doors_type", "overhead_doors_qty", "overhead_doors_lites", "overhead_doors_style", "overhead_doors_hi_lift_track", "low-head-room-kit", "door-opener"], "sketchPrimary"=>"overhead_doors_type"}

line.to_s # Throws Error: #<SystemStackError: stack level too deep> SketchUp:1:in `eval'
line # Crashes Sketchup
```

**Comment by thomthom** [comment]
I'm not able to reproduce.

Could it be some other extension or something that modifies `Hash#to_s` in a way that cause an infinite recursive loop? Seeing that you're getting a stack overflow error.

Does it crash for you only when pasted into the console? Or also when run from an `.rb` file?

Did you submit the BugSplat? If so, did you enter any details we can use to look it up?

**Comment by DanRathbun** [comment]
This is the only Windows Error Reporting report I could find that MIGHT be related. It's from 13 days ago, so I'm not sure.
[Critical_SketchUp_18_WER_Report.zip](https://github.com/SketchUp/api-issue-tracker/files/2379766/Critical_SketchUp_18_WER_Report.zip)

All the other reports are AppHang reports that have to do with a device context error when the internal notebook display is set as the secondary display when an external monitor is plugged in and set as the primary. When SketchUp opens on the secondary (internal) display0 and the desktop is extended onto it, SketchUp hangs at the point it is supposed to initialize the model viewport. This affects all versions supported by Win10 running on Win10, from v 16 on up. (I believe this was reported a cycle or 2 ago.)
Updating the Nvidia driver did not help.
Switching to the Intel integrated HD630 GPU did not help.
All was working fine (per the scenario above) with a recent Nvidia driver installed by Nvidia Experience "out of the box" from MSI. Then Windows 10 Home did an update and installed an older driver, which triggered the hanging behavior.
I've got all SketchUps back to working by setting the internal display back to the primary. (It doesn't matter as much on Win10 as it can display the taskbar on both displays.)

**Comment by cedarmora** [comment]
> Could it be some other extension or something that modifies Hash#to_s in a way that cause an infinite recursive loop?

Maybe? I do have Sketchup Make 2016 also and the code doesn't cause any problems there. If I run this:
```
line = {"id"=>"12", "name"=>"Overhead Doors", "repeat"=>true, "taxed"=>true, "crew"=>["building"], "fieldSuffixes"=>["overhead_doors_type", "overhead_doors_qty", "overhead_doors_lites", "overhead_doors_style", "overhead_doors_hi_lift_track", "low-head-room-kit", "door-opener"], "sketchPrimary"=>"overhead_doors_type"}

line.method(:to_s) # Says where methods are defined
```

in 2016, it outputs: `#<Method: Hash#inspect>`
in 2017, it outputs: `#<Method: Hash#to_s(inspect)>`

I tried calling `line.inspect` and that displays the same behavior as `line.to_s` in their respective Sketchup versions.

> Does it crash for you only when pasted into the console? Or also when run from an .rb file?

In console, no matter where the code is called, it crashes sketchup. If put the code in a ruby file, that runs immediately, it crashes the whole of sketchup make 2017 without warning. If I put it in a function, it just throws the same error, but doesn't crash sketchup:
```
Error: #<SystemStackError: stack level too deep>
SketchUp:1:in `eval'
```


> Did you submit the BugSplat? If so, did you enter any details we can use to look it up?

It doesn't give me the chance to, it just crashes immediately.

If I use the remote debugger from Visual Studio code, and pause after the `line` variable has been defined, I can call `to_s` from the debug console inside Visual Studio Code and it outputs just fine.

**Comment by thomthom** [comment]
Do you get the `SystemStackError` if you have no extensions loading? (With a pristine Plugins directory?)

**Comment by MSP-Greg** [comment]
Good
```ruby
puts "\nPicked was:\n#{picked.pretty_inspect}\n"
```
vs broke:
```ruby
puts "\nPicked was:"
puts pp picked
puts
```

`puts pp picked` is kind of a 'what should this do' statement, since `pp` is already outputting to STDOUT.  It's kind of like `puts puts something`.  Regardless, it shouldn't SEGV

**Comment by cedarmora** [comment]
@thomthom If no extensions load, I do not get the error when I try the test code in the ruby console.

**Comment by DanRathbun** [comment]
> `puts pp picked` is kind of a 'what should this do' statement, since `pp` is already outputting to STDOUT. It's kind of like `puts puts something`. 

I know. It was a case where I think I added the `pp()` later, and I really should have used `#pretty_inspect` instead. Why and how I got there isn't that important, now, as the double puts isn't the cause. _Read on ..._

> Regardless, it shouldn't SEGV

I ran down the cause. When my extension module's `debug` switch is `true`, it loads and extra testing file, along with a test menu. One of things it does is enumerate nested classes and push their names into an array. The array is used for building test menus to toggle debug and verbosity switches. Just before the submenus are built, I added a line that uses `#pretty_inspect` to output the array of class names. (It was actually only needed to verify the menu building was working, but I left it in.)

Anyhow, ... since this use of the prettyprint library occurs **during SketchUp startup** .. it somehow corrupts the Ruby stack and/or the Sketchup Ruby Console, which has some STDIO redirection going on.

When I replace it ...
```ruby
puts classes.pretty_inspect
```
... with a simple `array#join` call, ie, ...
```ruby
puts '[ ' << classes.join(', ') << ' ]'
```
... the instability goes away, ... and we can use `pp()` or `#pretty_inspect()` afterwards to our little heart's content.

----

So the instability seems to be with a clash between the SU2017 & SU2018 [`Console` object](http://ruby.sketchup.com/Sketchup/Console.html), and the Ruby [prettyprint](http://ruby-doc.org/stdlib-2.2.4/libdoc/prettyprint/rdoc/index.html) library.

* FYI, there was an issue (https://github.com/SketchUp/api-issue-tracker/issues/17) reported here concerning a regression in Console behavior.

@thomthom For THIS issue, here is a simplified test file: [TestIssue122.zip](https://github.com/SketchUp/api-issue-tracker/files/2384949/TestIssue122.zip)

It does **NOT** crash in SU2016 which uses Ruby **2.0.0**.
It **ONLY** crashes in SU2017 and SU2018 which use Ruby **2.2.4**.

I've disabled ALL plugins except this test file (even DC,) and it crashes, so there is no outside influence going on.

At the number 3 point (in the test), you can also type inspection commands into the console  and get crashes, as Cedar did, which was the impetus for this thread.

----

For those not wanting to download the `"TestIssue122.rb"` file, it looks like ...
```ruby
# encoding: UTF-8

require "prettyprint"
require "pp"

# Save this to file "TestIssue122.rb" and cause it to load when SketchUp starts.
# It's important that a prettyprint method call be made during the startup cycle.
#
# After loading, 
# 1. Fire command: Extensions > Test Issue 122 > inspect VALS
# 2. Note the SystemStackError in the Console. Ruby Stack is now unstable.
# 3. Again, fire command: Extensions > Test Issue 122 > inspect VALS
# 4. CRASH. NO BugSplat!, No Windows Error Report record.
#
module TestIssue122

  SKETCHUP_CONSOLE.show

  VALS = { :var1 => 'hi', :var2 => 'hello' }
  
  @@loaded = false unless defined?(@@loaded)
  
  while !SKETCHUP_CONSOLE.visible?
    sleep 0.3
  end

  # Use prettyprint library during SkethcUp's startup cycle:
  puts VALS.pretty_inspect

  # A test method to do an inspect to the console.
  # Evaluating this this method once or twice may cause the crash.
  def self.inspect_vals
    puts VALS.inspect
  end

  # A test method to do a pretty_inspect to the console.
  def self.pretty_inspect_vals
    puts VALS.pretty_inspect
  end

  unless @@loaded
    pmenu = UI.menu('Plugins')
    tmenu = pmenu.add_submenu('Test Issue 122')
    tmenu.add_item('inspect VALS') { self.inspect_vals }
    tmenu.add_item('pretty_inspect VALS') { self.pretty_inspect_vals }
    #
    @@loaded = true
  end

end # test module
```

**Comment by MSP-Greg** [comment]
@DanRathbun

Interesting.  Thanks for the info.

> Anyhow, ... since this use of the prettyprint library occurs during SketchUp startup .. it somehow corrupts the Ruby stack and/or the Sketchup Ruby Console, which has some STDIO redirection going on.

If you change it load on the 'first Menu/Toolbar click', does the issue go away?

This reminds me, there needs to be a `load_relative` method.  One can use `require_relative` for things like TestUp, which isn't scrambled/encrypted, but otherwise...

FYI, I've been busy building/testing OpenSSL 1.1.1 and tearing apart my trunk build system.  Not much SU lately.  Also, 'Ruby Core' is now testing against mingw builds, and also VC14, which (I think) is what 2018 is built with...

**Comment by DanRathbun** [comment]
> If you change it load on the 'first Menu/Toolbar click', does the issue go away?

**Good call**. No it does not.

If you comment out line 28, that uses `pretty_inspect()` during SkethcUp's startup cycle, and then before you do 1., you fire command: **Extensions** > **Test Issue 122** > **pretty_inspect VALS**, ...
then do step 1., ... the crash still happens.

Weirdly, ... if you first do a normal `inspect()` call before ever using a prettyprint method, then afterward you can either whenever, in whatever order, however many times as you choose with no crash.

**Comment by cedarmora** [comment]
The changes Dan made to our usage of the UI::HtmlDialog appear to have fixed the issue, so I closed it.

**Comment by DanRathbun** [comment]
Well there is an issue here. It is likely the SketchUp Console as is it known to have other bugs.
This may boil down to be a **documentation issue** to warn API users not to use prettyprint with the SU2017 and SU2018 consoles (as they will not get any more "love".)

The prettyprint library (I was surprise to discover) is pure Ruby, and executes slow iterators upon strings. Possible recursive iterations causing the stack overflow we've seen.

**Lesson:** Basically use the compiled `JSON.pretty_generate()` or `j()` or `jj()` methods instead (for hashes or arrays.) Or, log to a file or output externally to WinDebug or DebugView, etc.

**Comment by MSP-Greg** [comment]
The speed isn't really an issue, as the bottleneck may often be io...

`PP` is a more generalized framework for serializing an object, iow, `p` is just an alias to `puts`, but `pp` is more than simply an alias to `prettyprint`.  `PP` has `Thread` in it several times, and also `bind`.  `PrettyPrint` has neither.

Part of the issue with parsers is that they can have stack issues depending on the depth of the object being parsed.  Since `PP` is a generalized framework, it may be making use of things that work fine in stand-alone Ruby, but may have issues in SU and/or older windows Ruby versions.

So, does this issue exist when using `prettyprint` instead of `PP`?

Regardless, if it works in stand-alone Ruby, but not in the SU console...

**Comment by DanRathbun** [comment]
Good observations.

It was "pp" (hence `PP`) I was using, and specifically it's `pp()` and `object#pretty_inspect()` methods.

> So, does this issue exist when using prettyprint instead of PP?

I don't know, so I shouldn't then be blaming the `PrettyPrint` class. (my bad!)

I have looked at it's doc page, and it is not what I am interested in using. Too clunky for such simple use...
```ruby
# somewhere early in loading
@@pp = PrettyPrint.new

# Elsewhere throughout code and methods ...
@@pp.text(some_object.inspect).flush

# OR ... wrap that in our own local pp() method ...

def pp(object)
  @@pp.text(object.inspect).flush
end
```
I've already switched to using `JSON.pretty_generate()` for arrays and hashes, ... other types can use normal `#inspect`.

But it does give me the idea of using a custom local `pp()` method to call one or the other as needed.
