### ISSUE TITLE
Sketchup::View#write_image() - Document supported image file formats

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#156]
`Sketchup::View#write_image()` - Document supported image file formats.

The documentation does not explicitly state what image formats this method supports. (The examples show "png" and "jpg/jpeg".)

Attempts to write out an "eps" file fail and **`false`** is returned. Ie:
```ruby
Dir::chdir( UI::select_directory ) {
  Sketchup::active_model.active_view.write_image("test.eps",800,600,true)
}
```
http://ruby.sketchup.com/Sketchup/View.html#write_image-instance_method

-----
Migrated from docs repo issue tracker: https://github.com/SketchUp/ruby-api-docs/issues/17

**Comment by DanRathbun** [comment]
Just a question about the YARD output. 

Why are the backticks around the filetype extensions not rendering the text as monospaced font ?

**Comment by thomthom** [comment]
> Why are the backticks around the filetype extensions not rendering the text as monospaced font ?

Because by default YARD uses rdoc, not markdown. And our original documentation was also rdoc based. It's so easy to forget that you have to use `+` instead of the backticks. It's possible to configure YARD to markdown, which I've wanted to do, but it will require going over every single page and correcting incompatible syntax. Sometimes there isn't even 1:1 mapping of features.
