### ISSUE TITLE
Sketchup::Camera constructor arguments are all optional (defaults not listed for some)

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#160]
**`Sketchup::Camera`** constructor arguments are all optional. (The example shows using no args.)

But the first 3 args do not list the defaults. They are:
```
eye  = [0",0",1"] (Geom::Point3d,Array[Length,Length,Length]) - 1 inch directly above the ORIGIN.
                                                                regardless of model units.
target = [0",0",0"] (Geom::Point3d,Array[Length,Length,Length]) - looking at the ORIGIN.
up     = [0.0,1.0,0.0] (Geom::Vector3d,Array[Float,Float,Float]) - parallel to the Y axis.
```

**Comment by thomthom** [comment]
They are not all optional. You can either call it with no arguments at all - and get a default camera. But if you do provide arguments, then all the first three are non-optional.

This method needs two `@overload` signatures.

**Comment by DanRathbun** [comment]
Please reopen. The docs still do not list the defaults (as mentioned above.)

**Comment by thomthom** [comment]
hmm... you refer to the constructor without any arguments? It wouldn't be accurate to document them as having default values - because that implies that you can provide only some of them.

You have to provide all first three arguments, or none at all. They are not all optional.

But we can add a description of the values the camera will be initialized to if one is using the constructor without arguments.

**Comment by DanRathbun** [comment]
Description or Note, either would suffice.

**Comment by DanRathbun** [comment]
> @thomthom But we can add a description of the values the camera will be initialized to if one is using the constructor without arguments.

Please reopen (**again**,) as this has not been done.

**Comment by Eneroth3** [comment]
The methods has two overload signatures as discussed here. I'm not sure what's missing from the documentation.

**Comment by DanRathbun** [comment]
**(1)** I **clearly** explained and listed the missing information on **default properties** (ie, **eye** point, **target** point and **up** vector) in the [opening post](https://github.com/SketchUp/api-issue-tracker/issues/160#issue-376408826) of this issue.

Coders would surely like to know what these properties are when they create a [`Camera`](https://ruby.sketchup.com/Sketchup/Camera.html#initialize-instance_method) object without constructor arguments.

**(2)** I **quoted** Thomas (in [post 4](https://github.com/SketchUp/api-issue-tracker/issues/160#issuecomment-461400264)) stating **how** he thought the information should be added.

I agreed in [post 5](https://github.com/SketchUp/api-issue-tracker/issues/160#issuecomment-461713076).

----

AND ... **please** post a reason if manually closing an issue. If an issue has "_become stale_" ... perhaps **first** post a question asking the coder community whether the issue is still valid and why is should not be closed.

**Comment by thomthom** [comment]
The documentation already lists the two different ways of calling the method (0 and 3 arguments)
The default properties of objects isn't something we have ever documented (point, vector). When creating a camera I would expect you'd want to explicitly set all properties anyway, either via constructor or one by one later one.

Closing this as done (with the two overloads documented).

**Comment by DanRathbun** [comment]
I do not understand the obstinance with this **valid request**!

The [constructor's](https://ruby.sketchup.com/Sketchup/Camera.html#initialize-instance_method) **common** YARD docstring says ...
  > _Returns a new camera with eye (where the camera is) and targets (where the camera is looking)._

(Ie, each overload does not have it's own docstring, which is possible with YARD.)

Your documentation has a section labeled: **`> Default parameters`**, but has no information beneath it other than a code snippet that serves no real educational value.

This is the section that should contain the proposed information that the **current method docstring** refers to. It is totally valid to provide the information that this docstring refers to (ie the eye point, target, etc.,) in this **`> Default parameters`** section.

> @thomthom  _The default properties of objects isn't something we have ever documented (point, vector)._

**INCORRECT** 

There are only a hand full of classes in the API that we have direct constructor access, so setting a precedent is not a big deal.
(However, as noted below, the documentation has **already** set a precedent.)

For the [`UI::HtmlDialog`](https://ruby.sketchup.com/UI/HtmlDialog.html#initialize-instance_method) and [`UI::WebDialog`](https://ruby.sketchup.com/UI/WebDialog.html#initialize-instance_method) classes, **all of the default parameters** have always been documented.

[`SketchupExtension`](https://ruby.sketchup.com/SketchupExtension.html#initialize-instance_methodl), [`LanguageHandler`](https://ruby.sketchup.com/LanguageHandler.html), and the other 3 or 4 [`UI`](https://ruby.sketchup.com/UI.html) classes have only required parameters.

For [`Geom::Point3d`](https://ruby.sketchup.com/Geom/Point3d.html), both in the class introduction and in the [constructor](https://ruby.sketchup.com/Geom/Point3d.html#initialize-instance_method), your documentation tells what the default parameters are or do ...
>   ```ruby
>    # No arguments, creates a point at the origin [0,0,0]
>    pt1 = Geom::Point3d.new
>    ```

For [`Geom::Transformation`](https://ruby.sketchup.com/Geom/Transformation.html#initialize-instance_method) the result of the default has always been given (ie, the `IDENTITY` transformation.)

----

The precedent **IS** to give the API users the proper information. If I were to post your comments out on some APIist forum, I would bet there would be quite a few comments saying that it is bad API behavior to hide operational facts from API users.

For [`Geom::Vector3d`](https://ruby.sketchup.com/Geom/Vector3d.html), not passing arguments to the constructor will result in an **invalid** vector object, so should not really be allowed **without giving this fact**. The new vector object will not be valid until at least one of the X, Y, or Z components are explicitly set. 
**Following precedent (and good API behavior) this should be be noted in it's documentation**.

Also, for class [`Geom::LatLong`](https://ruby.sketchup.com/Geom/LatLong.html#initialize-instance_method) it should be noted that the default produces a loaction on the prime meridian, at the equator ...
```ruby
latlong = Geom::LatLong.new
LatLong(0.00000N, 0.00000E)
```

----

The takeaway here is that this request **is valid**, **follows precedent** and assumes **good API documentation behavior**.
It did not come "out of thin air" nor is it a so called "vanity request".

I did not invent these ideals. And I am having are time understanding why I have to defend these ideals to you Thomas or Christina.

This looks like a "sweep it under the rug" action so we can show our bosses we've reduced the open issue count.
It is ridiculous because you'd spend less time and money on it if you just cut and pasted the information into the docs and be done with it.

The time that is being spent arguing over every single issue is bloating the cost of maintaining the API documentation.

**Comment by Eneroth3** [comment]
We have fixed numerous Ruby API docs issues that will go live later, along with SketchUp 2021 changes. Some logged GitHub issues will however not lead to a change in the API docs. This is not to save work - as you say this conversation is more work than a change would be - but because some suggested changes do not improve the API docs.

There are no default values for these arguments to be documented. There is however an overload with no arguments, whose existence is already document. While it would technically be possible to explain in the method description what values SketchUp fall back to when none are specified, it would be inconsistent to Point3d, Vector3d, Point2d, Vector2d, InputPoint etc.

Some constructors do document what the default properties are for an object created with no argument, like Transformation.new generating an identity matrix, but that is because it is relevant. There are use cases for an identity matrix (even though the IDENTITY constant probably is clearer and more idiomatic). It is hard to think of a use case where you need a camera that just happens to match the arbitrary fall back properties, and in such hypothetical case it would be better to spend half a line of code clearly specify those values yourself than relying on such a niece and arbitrary detail. If you hypothetically would ever want a camera looking downwards from one inch above the origin, you can state that in your code, instead of expecting anyone maintaining the code to have to look that up.

HtmlDialogs and WebDialogs are different to Camera because the default values are very reasonable and commonly used, some probably more used than any alternative value. In these cases you don't even need to know a custom value can be specified to understand what the code does.

If brought up in an API forum, I'm sure a lot of people would have examples of API details that exist for historical reasons and aren't removed because it's not worth the effort and it could break things, but aren't document either because they are irrelevant and not good practice to rely on.

**Comment by DanRathbun** [comment]
Y'all don't have to write it as though there are "default arguments", ... just document what kind of object the constructor call without arguments produces. A simple sentence would be fine. ...

`"Creates a new perspective camera with 30 degree field of view, positioned 1 inch above the origin, looking directly downward, with the Y-axis pointing toward the top of the view."`

You might even be more specific and also add ...

`"It is expected the user code would afterward apply transformation(s) to move the camera to some other orientation(s)."`

----

FTR ... y'all are "splitting hairs". Just because there are no constructor method arguments being passed to **set object properties**, does **not** mean that the resultant objects are created without default property assignments.

**Properties** of objects are being set to default values, as I have shown in the case of several classes.

----

It is "plain and simple as mud".

**If a public API method creates an object, it's documentation should describe the state of the object created.**

**Comment by thomthom** [comment]
That default camera isn't really defined in the API layer though, it's an implementation detail. Arbitrary numbers to have a an object with valid state.

**Comment by DanRathbun** [comment]
Okay, now we are getting somewhere, so then ...

Firstly, ... since you purport there to be no default parameters when none are passed, the section label "**> Default parameters**" should be removed or changed to **"Example with no parameters"**.

----
Secondly, ... this section docstring could be:

>Example with no parameters:
> ```ruby
> camera = Sketchup::Camera.new
> ```
> **Creates a new valid camera object in an arbitrary orientation, with arbitrary properties.**
> **(The states of this camera's properties are not contracted to remain as is in later API versions.)**

You've said as much for other things in the API that you didn't want coders relying upon.

;)

**Comment by Eneroth3** [comment]
To me calling it a "Default camera" or "Camera with no parameters" makes a lot more sense "Default parameters".

Btw, "Default parameters" technically isn't a section label but an example label. I agree YARD makes it too prominent and gives the impression more things belong under that header, a bit like an overload, and this is probably why I avoid labeling examples.

**Comment by DanRathbun** [comment]
I think any use of the word "default" would make future coders ask what the property values are.

Thomas' idea of using "arbitrary" does a better job of expressing that the properties values should be viewed as unimportant.
