### ISSUE TITLE
Sketchup::Curve#length() getter describes return value from Length#to_s

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#196]
[**`Sketchup::Curve#length()`**](http://ruby.sketchup.com/Sketchup/Curve.html#length-instance_method) getter describes return value from  [**`Length#to_s`**](http://ruby.sketchup.com/Length.html#to_s-instance_method) method that may cause confusion.

The main caption reads:
> `#length => Object`

... when it should give class `Length` as the return value.

It's "Returns" section value says ...
> * _length - the length of the curve in current units if successful_.

It should **NOT** say "**in current units**" as the method returns a [**`Length`**](http://ruby.sketchup.com/Length.html) object, which is **ALWAYS** in inches.

(I think the error may have come from someone calling the method at the console, and seeing the output from [**`Length#to_s`**](http://ruby.sketchup.com/Length.html#to_s-instance_method) and not understanding that the console STDOUT gets the output of an object's **`#to_s`** method in order to display it as a string representation.)

It should also use the proper YARD means of giving the return class as [`Edge#length`](http://ruby.sketchup.com/Sketchup/Edge.html#length-instance_method) was changed to show for issue #153.

.

**Comment by Eneroth3** [comment]
It's not just this method; it's all over the documentation. I've thought about going over these myself but never gotten around to do it.

As it is now the docs actually says methods returning Lengths return different values based on model units, which could cause new developers to get all sorts of ideas about how lengths are actually handled in SketchUp. SketchUp is the only 3D program I know of with a hardcoded unit and conversion done at the input/ouput layer.

This said, I don't think the docs should say length in inches as return value for all these methods. It's better to just say Length, and then let the documentation for the Length class explain how inches are used internally. I very rarely think of Length being in inches, due to how seamless the conversion is, and think this would be quite verbose to explain this all over the documentation.

**Comment by DanRathbun** [comment]
> It's not just this method; it's all over the documentation.

I know but we have to **file an issue for each one**, or they don't get corrected.
The last cycle I filed a handful and they were fixed. See this one (was #153.)
http://ruby.sketchup.com/Sketchup/Edge.html#length-instance_method

> This said, I don't think the docs should say length in inches as return value for all these methods.

I have not proposed that they do in previous issues, and the fixes have not.

Referring to the previous fix, **was this fix acceptable ?**

----

So as you find methods docs that have not yet been fixed, please file issues for them.
