### ISSUE TITLE
Edge.split description has too many to's and the wrong type too

### ISSUE THREAD

**Issue by MaschMaker** [SketchUp/api-issue-tracker#227]
The first sentence in [Edge.split](http://ruby.sketchup.com/Sketchup/Edge.html#split-instance_method) method needs fixing.

The current text reads:
> The split method is used to **_to_** split an edge into **_to_** or more distinct edges.

The 2nd "to" should be deleted and the 3rd "to" should be "two", giving:

>  The split method is used to split an edge into two or more distinct edges.

**Comment by rickmas** [comment]
@thomthom , thanks for moving this issue from https://github.com/SketchUp/ruby-api-stubs/issues for me.  I got a message from DanRathbun to move it but you've already done it!

I created the issue in ruby-api-stubs only because http://ruby.sketchup.com/index.html (at the bottom) says this is where documentation bugs should be tracked. Looks like that is another issue....

**Comment by thomthom** [comment]
@rickmas - thanks for the heads up. I'll correct that. We changed how we work with the issue trackers. We found it was easier to have documentation issues side by side with bugs and features.

**Comment by DanRathbun** [comment]
One stop shopping 😉

**Comment by DanRathbun** [comment]
This issue needs to be reopened as only the second half of the issue was fixed.
(Ie, the double "to to" still exists in the 1st sentence.)
