### ISSUE TITLE
Buggy Sketchup::Material from Sketchup::Image

### ISSUE THREAD

**Issue by noelwarren** [SketchUp/api-issue-tracker#228]
SketchUp 2018
Windows

Materials Observer gives handle on SketchUp::Image's material  that can then be assigned to entities in an unexpected manor.

It should not be possible to assign Sketchup::Image materials to entities.

```ruby
class GhostMaterialObserver

    def onMaterialAdd(materials, material)
        puts [:onMaterialAdd, material, materials.include?(material)].inspect
        face = Sketchup.active_model.entities.add_face([0,0,0],[0,100,0],[100,100,0],[100,0,0])
        face.material = material
        return if materials.include?(material)
        puts "Oh, look!  #{material} is assigned to #{face}, yet is not in #{materials}"
    end

end
Sketchup.active_model.materials.add_observer(GhostMaterialObserver.new)
```
Copy and paste the above snippet into the ruby console and then drag an image file into the sketchup viewport.  Some output will be printed in the console describing the buggy behavior.

**Comment by noelwarren** [comment]
Related issue: https://github.com/SketchUp/api-issue-tracker/issues/180

**Comment by DanRathbun** [comment]
But we are also cautioned repeatedly about not modifying the model within observer callbacks.
However the callback could just set the image material reference to an external variable, and later (outside) you could still demonstrate the illegal face materiel assignment.

But eliminating the observer question ... with a image instance inserted and selected in SketchUp ...
```ruby
img  = Sketchup.active_model.selection[0]
idef = Sketchup.active_model.definitions.find{|d| d.instances.include?(img) }
imat = idef.entities.grep(Sketchup::Face).first.material
```
... then draw a face and select it, and assign the image material ...
```ruby
face = Sketchup.active_model.selection[0]
face.material= imat
```
**So the bug seems to be with the [`Sketchup::Drawingelement#material=`](http://ruby.sketchup.com/Sketchup/Drawingelement.html#material=-instance_method) instance method, not the observer reference passed into callback methods.**

**Comment by DanRathbun** [comment]
We might also add some documentation for post SU2018, that the valid way is to create a new material via [`Sketchup::IImageRep`](http://ruby.sketchup.com/Sketchup/ImageRep.html) class ...
```ruby
model = Sketchup.active_model
img  = model.selection[0]
img_rep = img.image_rep
matl = model.materials.add("New Name")
matl.texture= img_rep
```
Coders may still need to have reference to the image's material (and texture) in order to copy some properties from the texture  into the new material.

Of course this all would be easier if there was some kind of cloning method ...
*  **`Sketchup::Materials # new_from_image(`_`name, image`_`)`**

?

**Comment by DanRathbun** [comment]
Did you add the Image_Rep code snippet to the docs ? Or do you wish a new doc issue opened ?

**Comment by thomthom** [comment]
Don't think that example was added no. Will log a new issue for that.
