### ISSUE TITLE
Documentation issue - Color "Gainsboro" has extra comma

### ISSUE THREAD

**Issue by MaschMaker** [SketchUp/api-issue-tracker#233]
There is an extra comma ending the RGB color value for [Gainsboro](http://ruby.sketchup.com/Sketchup/Color.html).

Current value is 
```
220,220,220,
```
I'm using the color table to generate a comparison with another system color table and this one created a mismatch until I noticed the extra comma.

**Comment by DanRathbun** [comment]
This is an error in the value in the HTML table file used for the `Sketchup::Color` class' YARD doc page. It is not an API bug. (The HTML table is manually authored and a separate file, which is inserted by YARD when it generates the documentation page for the class.)

> I'm using the color table to generate a comparison with another system color table and this one created a mismatch until I noticed the extra comma.

You should not be using the webpage to do this. You should be using the API Color class' methods to generate an actual data set. (Ie, colors could be added later.)
```ruby
color_names = Sketchup::Color::names
```
For an array of arrays ...
```ruby
color_data = color_names.map {|name|
  color = Sketchup::Color.new(name)
  [ name, color.red, color.green, color.blue ]
}
```
For a hash with color names as the keys, values being RGB integer arrays ...
```ruby
color_data = {}
color_names.each {|name|
  color = Sketchup::Color.new(name)
  color_data[name]= [ color.red, color.green, color.blue ]
}
```

**Comment by rickmas** [comment]
I'm importing svg files into Sketchup and needed to know if the set of named colors allowed in an svg file was the same set used by Sketchup.  I was using the documentation for this analysis.

I found out that the svg specifications match the sketchup color names, almost.  SVG uses both spellings for gray (either "gray" or "grey") whereas sketchup does not.  And unfortunately, sketchup is not consistent in one case.  Sketchup uses the spelling "LightGrey" when all other spellings of this color are done with the "a", not the "e".  Since I'm importing svg content, I need to ensure I can decipher both spellings.

I mentioned that this was a documentation issue in the title (not an api bug).  Is this the correct location for documentation issues?  Hopefully, the HTML table author you mentioned can fix the errant comma.

I appreciate the time you took to give those code examples.  thanks!

**Comment by thomthom** [comment]
> Is this the correct location for documentation issues?
Yes.

**Comment by DanRathbun** [comment]
> Since I'm importing svg content, I need to ensure I can decipher both spellings.

And since SketchUp recently added SVG toolbar button support, and is likely to add more SVG support in other areas in the future, ... I filed an enhancement issue to update the color names.

_See:_ https://github.com/SketchUp/api-issue-tracker/issues/235
