### ISSUE TITLE
C API Method SUSectionPlaneIsActive crashes on MacOS / OSX

### ISSUE THREAD

**Issue by chegarty3** [SketchUp/api-issue-tracker#274]
The C API method SUSectionPlaneIsActive crashes when used on MacOS. The method works correctly on Windows 10.

The following code results in a crash for any section plane on MacOS. The same method call works on Windows 10.

```
bool IsSectionActive(const SUSectionPlaneRef& plane)
{
bool is_active = true;
SUSectionPlaneIsActive(plane, &is_active);
return is_active;
}
```
I know when this was happening with Windows it was because the link library I was using (from the SDK) didn't have some of the proper symbols exported and when I updated to a new library it was fine.  So maybe the library in the MacOS SDK is also the wrong one?

**Comment by thomthom** [comment]
I'd had time to look into this. And yes - it's exactly the same. And I realize we're completely missing proper docs for how to user the live C API.

On the mac, if you link against SketchUpAPI.framework you run into the same issues as linking to SketchUpAPI.lib on Windows. You get duplicate symbols and eventually things will not work properly or crash. In this case there is a dynamic downcast that fails because it's trying to downcast a type from another binary. Same thing with #273 - the dynamically generated loops for cut opening is not happening because of conflicting symbols.

For Live C API on Mac you don't link against the framework, but add it's path to the Framework Search Path - to allow XCode to find the headers. Then set the Bundle Loader to point to the SketchUp binary: `/Applications/SketchUp 2019/SketchUp.app/Contents/MacOS/SketchUp` - that will prevent linker errors since you are not linking against the framework.

However, it appear that while all the symbols for the C API is exported on Windows - they aren't getting exported on Mac. Only the `SUGetExtensionLicense` symbol is exported. So we have to fix that.

Once I made a build that exported all the functions this crash went away and #273 also worked as expected.

**Comment by chegarty3** [comment]
Is the updated SDK available in the 2019 Beta 2 release?

**Comment by chegarty3** [comment]
I need additional build instructions.  When I use the -bundle_loader option as indicated, I'm getting a new dependency error:
ld: file not found: @executable_path/../Frameworks/BugSplat.framework/Versions/A/BugSplat for architecture x86_64
Sorry, I'm very far from an XCode expert so the answer may be simple.

**Comment by thomthom** [comment]
Have you tried the "ruby license example" in the SDK package? Does that build for you (with my instructions earlier in this thread?)
