### ISSUE TITLE
SketchUp crashes when attempting to load component made in newer version

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#30]
When trying to load a model created in a newer version of SketchUp using the Ruby API, SketchUp crashes with a bugsplat. I would expect an IOError to be thrown.

Tested in SketchUp 2018, 2017 and 2016.

Bugsplats have been submitted.

```ruby
# First save a file from a newer version, then open an older version, run this code and locate the file.
Sketchup.active_model.definitions.load(UI.openpanel)
```

This is a quite severe issue for me as an extension developer as there is no way with the Ruby API to detect what version an external file is created in. For that some standalone executable checking the file would be needed.

**Comment by DanRathbun** [comment]
> @Eneroth3 This is a quite severe issue for me as an extension developer as there is **no way with the Ruby API** to detect what version an external file is created in.

Every SKP file begins with a sequence like this ...
```text
໿SketchUp Model﻿௿{13.0.4124}湵ધ ...
```
So we can use the **`File`** (**`IO`**) class to get the version string between the curlies ...
```ruby
def skp_version(
  path = UI.openpanel("Choose SKP file ...","*.skp"),
  verbose = false
)
  verstr = File.open(path,"r:ASCII-8BIT") {|f|
    ver  = ''
    char = ''
    char = f.readchar until char == '{'
    puts "{ detected" if verbose
    char = ''
    begin
      char = f.readchar
      if char != '}' && char != "\0000" && char != "\x00"
        ver << char
        puts char if verbose
        puts ver if verbose
      end
    end until char == '}'
    puts "last char: #{char}" if verbose
    ver
  }
  puts "The version string is: #{verstr}" if verbose
  verstr
end
```

**Comment by Eneroth3** [comment]
This is great Dan!

The underlying bug still should be fixed, but this makes my life easier!

**Comment by MSP-Greg** [comment]
@Eneroth3

This should work also (the regex is pretty 'tight'):

File.binread(path, 64).gsub(/\x00/, '')[/\{([\d.]+)\}/n, 1]

**Comment by DanRathbun** [comment]
> @MSP-Greg This should work also (the regex is pretty 'tight')

Works better in fact. I started with `#binread` but it didn't work for me, so I switched to the character iteration so I could see what each character was, and then realized there were null bytes embedded in there (C strings?)
So I added that to the exclusion expression and it worked, so I posted what I had. (It was late.)

**I fully expected there'd be more concise paradigms for this.**

If I'd have gotten back to `#binread` I'd likely have done something like this ...
```ruby
def skp_version(
  path = UI.openpanel("Choose SKP file ...","*.skp")
)
  File.binread(path,64).delete("\x00").scan(/\{(\d+.\d+.\d+)\}/n).flatten.first
end
```
... **because**, ... I've been using [**`String#scan`**](http://ruby-doc.org/core-2.2.4/String.html#method-i-scan) a lot lately, and ... I never before paid any mind to forms 4, 5 and 6 of [**`String#[]`**](http://ruby-doc.org/core-2.2.4/String.html#method-i-5B-5D). I didn't notice them! My mind was always on indexes and ranges whenever I looked at the docs. And the RegExp forms never registered on me.

**I love it!** It's so much more elegant and succinct than the [**`String#scan`**](http://ruby-doc.org/core-2.2.4/String.html#method-i-scan) method.  

But I think I like the `#slice()` alias a bit better on the end of a long call chain like ...
```ruby
def skp_version(
  path = UI.openpanel("Choose SKP file ...","*.skp")
)
  File.binread(path,64).delete("\x00").slice(/\{([\d.]+)\}/n,1)
end
```
Not that it makes much difference.

Dont'cha just love Ruby's flexibility ?

**Comment by DanRathbun** [comment]
> @Eneroth3 The underlying bug still should be fixed ...

Agreed. 

I wonder when this began happening. **Tested ...** 

-----

SketchUp 2015  upon load attempt of newer component versions ...
**... BugSplat!**

-----

Sketchup 2014 upon load attempt of newer component versions ...
```text
Error: #<RuntimeError: Can't insert empty component.>
<main>:in `load'
<main>:in `<main>'
-e:1:in `eval'
```
**... and after the error despite no component added ...**
```ruby
Sketchup.active_model.modified?
#=> true
```

-----

SketchUp 2013 upon load attempt of newer component versions ...
```text
Error: #<RuntimeError: (eval):0:in `load': Can't insert empty component.>
(eval)
(eval):0
```
... **and the model is not modified by the exception.**

-----

SketchUp 8 upon load attempt of newer component versions ...
... **no exception, no bugsplat, nothing imported, nothing output to console.**

-----

:nerd_face:

**Comment by thomthom** [comment]
Logged as SU-38577

**Comment by DanRathbun** [comment]
I really wished that y'all had made this a `SketchUp::SkpFileVersionError` (subclass of `RuntimeError`).

**Comment by thomthom** [comment]
Yea, the SketchUp API haven't defined any custom errors - always reused the native Ruby error types. Been temped to add new types. But been uncertain how that would affect the API docs, with a bunch of error classes. It's already pretty crowed. I guess the error classes could be omitted from having their own page, and just references as a possible error type for the relevant methods.

**Comment by Eneroth3** [comment]
I think we are already beyond the point where the API docs are so crowded you no longer can get a simple overview of them. Especially since LayOut was added.  I don't know if I had been able to casually play around with the API and slowly learn how to develop extensions if I had started today. However that is a different issue; one that I think needs a solution regardless of error handling.

**Comment by jiminy-billy-bob** [comment]
(I agree, the old docs were much easier to grasp for beginners)

**Comment by DanRathbun** [comment]
> I guess the error classes could be omitted from having their own page, and just references as a possible error type for the relevant methods.

But the main thing is that in methods the `@raise` YARD tags need to be able to display the exception subclass, so hiding them from YARD would not work.

If you wish to group them together, then encapsulate them all in a submodule. 
`Sketchup::Whoops`,  `Sketchup::Errors` or `SketchUp::Exceptions` or whatever name makes sense.

Then they'll be collapsible in YARD's left column nav pane. (Look at the `Http` classes.)

The main reason for having well named custom exceptions is better more readable rescue clauses, that evaluate faster because they do class identity comparison, rather then force coders to use slow error message string comparison, in order to decide how to handle exceptions.

**Comment by thomthom** [comment]
> But the main thing is that in methods the `@raise` YARD tags need to be able to display the exception subclass, so hiding them from YARD would not work.
I didn't mean hiding them from `@raise` tags, but omitting having a full documentation page for them. Avoiding them being in the class list. I don't really see much point of having a page for error classes.

> Especially since LayOut was added.
Yea, I wish the YARD template would have a feature to remember what section you collapse or not.

> I don't know if I had been able to casually play around with the API and slowly learn how to develop extensions if I had started today.
hah! When I got started the issues was lack of documentation - lots of things were omitted.

**Comment by Eneroth3** [comment]
> hah! When I got started the issues was lack of documentation - lots of things were omitted.

It was quite bad when I started too, but I could at least get an overview of everything there was and somewhat get an idea of how all these pieces fit together. While the grouping into categories may not have been showing actual relations between classes, it sure was quite pedagogical. Having little to no experience in coding and visit the documentation today must be like reading a thesaurus in an unknown language.

**Comment by thomthom** [comment]
I added a new issue to track the documentation organisation: https://github.com/SketchUp/api-issue-tracker/issues/199
