### ISSUE TITLE
SUImageGetName() returns empty string

### ISSUE THREAD

**Issue by tommash** [SketchUp/api-issue-tracker#303]
1. SketchUp Version: 19.2 Initial
2. OS Platform: Win

SUImageGetName() function returns an empty string. I was expecting it to return "Image", "Image1" (a name of a definition in ComponentDefinitions that describe the geometry on an image) same as in C++ SDK pImage->get_Name(&imageName); was doing.

```c
SUModelRef mod = GetSUModelRef();
SUEntitiesRef ents = SU_INVALID;
SUModelGetEntities(mod, &ents);
size_t count;
std::vector<SUImageRef> images(count);
if (SUEntitiesGetImages(ents, count, &images[0], &count) == SU_ERROR_NONE && count>0)
{
	CSUString name;
	SUImageGetName(images[0], name);
	std::string test(name.utf8());
}
```

I am afraid the name is in C SDK and was in C++ SDK the only key to find a proper definition among SUModelGetNumImageDefinitions().
We do not have SUImageGetComponentDefinition() or something similar.

**Comment by DanRathbun** [comment]
Also ... [component_defintion.h](http://extensions.sketchup.com/developer_center/sketchup_c_api/sketchup/component__definition_8h_source.html), line 78, has no `SUComponentType_Image` member to use with
the [`SUComponentDefinitionGetType`](http://extensions.sketchup.com/developer_center/sketchup_c_api/sketchup/component__definition_8h.html#a505693ced495c0b1ce65acee8b3ffd04) function so as to filter an array of definitions.

```c
enum SUComponentType {
          SUComponentType_Normal,  //< Regular component definition
          SUComponentType_Group    //< Group definition
    };
```

**Comment by DanRathbun** [comment]
@tommash , Have you tried:

**(1)** To cast the `SUImageRef` to a `SUDrawingElementRef`, and then cast to a `SUGroupRef` and then use the `SUGroupGetDefinition` function ?

**(2)** To cast the `SUImageRef` to a `SUEntityRef`, and get it's persistent ID (as a search target) via the [`SUEntityGetPersistentID`](http://extensions.sketchup.com/developer_center/sketchup_c_api/sketchup/entity_8h.html#ae2407126a43b9cb725fcd01401ef121c), ...
and then get the model image definitions array via [`SUModelGetImageDefinitions`](http://extensions.sketchup.com/developer_center/sketchup_c_api/sketchup/model_8h.html#aa37844f2eeaf1caff2e7fdfde56a0650) and iterate it, (skipping any with no instances,) and find the definition whose instances contain the instance whose persistent ID matches the target ID. 
When found then get the definition's name property.

**Comment by thomthom** [comment]
Within a model's session it'd be safe to use the entityID as well to check if two refs are the same, that's be usable for all entities, not just the subset that have PIDs.

But `SUModelGetImageDefinitions` SketchUp 2019, API 7.0, so that is limiting version compatibility more than PIDs.

**Comment by thomthom** [comment]
Turns out you cannot cast the image to an entity and back to a component instance or group. The C API will only return an invalid reference. We clearly have some inconsistent behaviour there. And we should have `SUImageGetDefinition`.

However, meanwhile I found a dirty little hack that will save you from looping over the whole definition list:

```cpp
SUImageRef image = GetImage();
// HACK! This digs into implementation details, so avoid unless there are no other options!
//   Reassign the pointer for the image ref directly to the component instance ref.
//   From there you can fetch the definition.
SUComponentInstanceRef instance = { image.ptr };
```

Complete example:

```cpp
VALUE image_definition_name() {
  auto model = GetActiveModel();

  SUEntitiesRef entities = SU_INVALID;
  SU(SUModelGetEntities(model, &entities));

  size_t num_images = 0;
  SU(SUEntitiesGetNumImages(entities, &num_images));

  std::vector<SUImageRef> images(num_images, SU_INVALID);
  if (num_images > 0) {
    SU(SUEntitiesGetImages(entities, num_images, images.data(), &num_images));
  }

  VALUE names = rb_ary_new();

  for (const auto& image : images) {
    // This won't work, SUComponentInstanceFromEntity will filter out groups
    // and image instances:
    //SUEntityRef entity = SUImageToEntity(image);
    //SUComponentInstanceRef instance = SUComponentInstanceFromEntity(entity);
    // HACK! Clean this up once the SU C API have better cast support between
    //       instance types.
    SUComponentInstanceRef instance = { image.ptr };
    assert(SUIsValid(instance));
    SUComponentDefinitionRef definition = SU_INVALID;
    SU(SUComponentInstanceGetDefinition(instance, &definition));
    SUStringRef name_ref = SU_INVALID;
    SU(SUStringCreate(&name_ref));
    SU(SUComponentDefinitionGetName(definition, &name_ref));
    auto name = GetString(name_ref);
    SU(SUStringRelease(&name_ref));
    rb_ary_push(names, GetRubyInterface(name.c_str()));
  }

  return names;
}
```

**Comment by thomthom** [comment]
I also found why `SUImageGetName` doese't return the definition, it returns the instance name. And the SU UI doesn't even let you set the instance name. Not even the Ruby API does this.

So it's only `SUImageSetName` that can even set the instance name.

This is a bug - and these two functions are currently broken. We'll have to change them to return the definition name.

**Comment by tommash** [comment]
The hack works brilliantly. Image export restored.

**Comment by DanRathbun** [comment]
> I also found why `SUImageGetName` _doesn't_ return the definition, it returns the instance name.

Obvious, that it should, but ...

> And the SU UI doesn't even let you set the instance name. Not even the Ruby API does this.

**Which I never realized!** I assumed because it is a special kind of instance, (that can via the API have multiple instances added,) that each should be able to have their own instance name property.

I see that the image instance name in Entity Info is _**displayed as**_ the image filename.
After dropping an image file, the `Sketchup::Image`'s definition name is the generic `"Image"`, `"Image#1"`, `"Image#2"`, _etc_.

**So what should happen in the future ?**

Should naming Image instances (getter and setter) be added to the UI, and both APIs ?
Or not and the instance getter just return the definition's name property?

> So it's only SUImageSetName that can even set the instance name.
> This is a bug - and these two functions are currently broken. We'll have to change them to return the definition name.

I know Thomas' suggestion would mesh with what is current, but it would also "paint the API into a corner" and cause issues later on if unique image instance names are later desired.

**I would suggest instead** to implement new methods `SUImageDefinitionGetName` and  `SUImageDefinitionSetName` (which would be convenience wrappers from an image instance object to it's definition's `SUComponentDefinitionGetName` and  `SUComponentDefinitionSetName` functions.)

**ALSO**, after having dropped images into SketchUp, _weirdly_ it looks as though the image name is saved into the instance name property, **but the definition path property is empty!**
I would suggest expose the instance name property, and begin saving the image path into the definition's path property.

> Turns out you cannot cast the image to an entity and back to a component instance or group. The C API will only return an invalid reference. 

I actually suggested casting to a `SUDrawingElementRef` and then to a component instance or group. **But I'll assume the same thing happens.**

**Comment by DanRathbun** [comment]
C API doc ...
> Warning
*** Materials from SUImageRef and SULayerRef should not be applied to any other entity in the model. They are uniquely owned by the image or layer.

No crash happened (yet) when using the Ruby API to add another instance of an image definition to  a model (SU2018.) Now both instances use the same hidden material, but have differing transforms.

IS this likely to destabilize the model ?

**Comment by tommash** [comment]
> IS this likely to destabilize the model ?
It is impossible to find such a material from Ruby by name. I was wandering how this can happen that user gives me a file in which a face is using a hidden material. I think it should not be allowed.

**Comment by DanRathbun** [comment]
> I was wandering how this can happen that user gives me a file in which a face is using a hidden material. I think it should not be allowed.

And Trimble thinks so also, ... that they [fixed this in v2019.2](http://ruby.sketchup.com/file.ReleaseNotes.html#label-Ruby+API+Additions+and+Improvments) ...

> _Added checks to prevent Image materials from being assigned to normal drawing elements. Doing so will now throw an ArgumentError_

What the release notes do not say is if Fix Errors will fix these misassigned materials ?

**Comment by thomthom** [comment]
> I would suggest instead to implement new methods SUImageDefinitionGetName and SUImageDefinitionSetName (which would be convenience wrappers from an image instance object to it's definition's SUComponentDefinitionGetName and SUComponentDefinitionSetName functions.)

By adding `SUImageGetDefinition` the API user will be able to set the definition name. No need for additional proxy methods.

I think we'll mark `SUImageGetName` and `SUImageSetName` as deprecated. That way, if the UI expose instance naming for images we can deprecate them. I don't know why these functions were exposed in the first place, since you cannot even name the image definitions via the UI.

> No crash happened (yet) when using the Ruby API to add another instance of an image definition to a model (SU2018.) Now both instances use the same hidden material, but have differing transforms.

Adding another instance isn't the problem. The problem is using the material owned by the image and applying it to drawing elements in the model. This has happened in the past by for instance people traversing all definitions in Ruby and fetching the faces and its material applying it else where. 

> What the release notes do not say is if Fix Errors will fix these misassigned materials ?
I'm not sure... I don't think so...

**Comment by DanRathbun** [comment]
> I think we'll mark SUImageGetName and SUImageSetName as deprecated. That way, if the UI expose instance naming for images we can **deprecate** them.

I think you meant **re-implement** them.

All in all good enough.

> I don't know why these functions were exposed in the first place, since you cannot even name the image definitions via the UI.

Well exposing the instance name is a good idea as finding a particular instance by name in a common pattern. (We'll save it for it's own feature request.)

 Currently the workaround would be to encapsulate the Image object inside a component and then name the component instances. **So it's not likely to ever be high priority**.

**Comment by taustin73** [comment]
SKOR-11823

**Comment by DanRathbun** [comment]
FTR ... 

> @thomthom :
> _By adding [`SUImageGetDefinition`](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_image_ref.html#ad7934297e8a6bb8acc22046cbd696d77) the API user will be able to set the definition name._ 
>  ... _I think we'll mark [`SUImageGetName`](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_image_ref.html#afc1ce3d4ef11e284a075286f8dd33543) and [`SUImageSetName`](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_image_ref.html#a74f369f83d8d481a21dd4013d8b7975d) as **deprecated**._

... the above happy things happened with the SketchUp **2021.**1, **C API 9.1** release.
