### ISSUE TITLE
Add example of converting an Image to a Material

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#307]
https://github.com/SketchUp/api-issue-tracker/issues/228#issuecomment-476357184

```ruby
model = Sketchup.active_model
img  = model.selection[0]
img_rep = img.image_rep
matl = model.materials.add("New Name")
matl.texture= img_rep
```

**Comment by Eneroth3** [comment]
Should this be an example of things you can do with ImageRep or with Image?

**Comment by thomthom** [comment]
Its for providing an example on how one can convert a `Sketchup::Image` to a `Sketchup::Material` without saving texture to a temp file.

**Comment by thomthom** [comment]
Not sure where exactly the example makes the most sense, in `Sketchup::Image` class documentation or `Sketchup::Image#image_rep` documentation. Maybe class documentation since the method would require that you knew which method to look at.

**Comment by DanRathbun** [comment]
Yea, this is needed because modifying the image objects could crash SketchUp.

Coders wanted a way to use an image's texture for a material, and since [`ImageRep`](https://ruby.sketchup.com/Sketchup/ImageRep.html)'s exposure to the API it has become a better pattern.

However, I think we can agree that the snippets that use the "I just happen to know that the first item in \<collection\> is a \<type of object we want for example\>" is a poor practice for examples.

I'd rather see a ...
```ruby
img = ents.grep(Sketchup::Image).first
```
... or similar shown for getting a reference, ... or just a comment like ... 
"Where `img` is a reference to an existing `Image` object" ...

**Comment by thomthom** [comment]
+1 for grepping the first image (makes it more robust)

**Comment by DanRathbun** [comment]
> Not sure where exactly the example makes the most sense, in Sketchup::Image class documentation  ...

And this is where the example now lives.
