### ISSUE TITLE
Set scene visibility for entity

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#376]
What I can see there is no way to set the scene visibility for a specific instance, only for layers, although this data is saved to the scene.

I propose `Page#set_visibility` to be given an overload where it accept an entity (DrawingElement) as its first parameter, in addition to layer.

**Comment by thomthom** [comment]
hmm...

strange. There are getters `hidden_entities` and `layers`. I would have thought there should be `hidden_entities=` and `layers=`.

**Comment by Eneroth3** [comment]
Here's a practical use case where this would be quite very much needed: Eneroth Scene Visibility.

![2019-11-26_19h27_27](https://user-images.githubusercontent.com/5631725/69661822-60433980-1083-11ea-8223-91060d5e558d.gif)

**Comment by DanRathbun** [comment]
>  I would have thought there should be `hidden_entities=` and `layers=`

Bulk setters certainly would be welcomed by coders.

I'd say that `hidden_layers` for the getter is more descriptive. 
Perhaps the former could be implemented as an alias ... and `layers` deprecated?

Thomas, I need to remind you that "=" named setters are not _normally_ used in Ruby when the argument is not a single object. Please remember how the [`Sketchup::View#camera=`](http://ruby.sketchup.com/Sketchup/View.html#camera=-instance_method) method always confuses coders when they wish to use a transition. They always make a mistake and try to pass 2 parameters instead of wrapping them inside 1 array.

**So**, when the argument(s) will be an array or list of variable size, ... then a non "=" method beginning with "`set_`" is probably more appropriate. (An exception to the rule would be when the argument is a fixed size array. For example a setter the expects a point but can also take an array of 3 numerics.)

I also would think that any layers **not specified** should be left unchanged. Ie, it'd modify the  hidden layer set, but not overwrite it. Unless anyone can think of a good reason to _allow_ an initial boolean argument that decides whether or not to overwrite the entire set?

The alternative would be to have 2 methods `set_hidden_layers` (overwrites and resets the set of a page's hidden layers to only the argument list,) ... and `add_hidden_layers` (modifies the current set of a page's hidden layers.

Test ...

```ruby
module PageRefinement

  refine Sketchup::Page do
  
    alias_method(:hidden_layers,:layers)  

    def add_hidden_layers(*ary)
      bulk_set_layers(ary.flatten,false)
    end

    def clear_hidden_layers()
      self.hidden_layers.each { |layer|
        self.set_visibility( layer, true )
      }
    end

    def remove_hidden_layers(*ary)
      bulk_set_layers(ary.flatten,true)
    end

    def set_hidden_layers(*ary)
      clear_hidden_layers()
      bulk_set_layers(ary.flatten,false)
    end

    private

    def bulk_set_layers(ary,flag)
      ary.each { |layer|
        case layer
        when Sketchup::Layer
          self.set_visibility( layer, flag ) if self.parent.include?(layer)
        when String
          self.set_visibility( self.parent[layer], flag ) if self.parent[layer]
        end
      }
    end

  end

end
```

**Comment by Eneroth3** [comment]
> I'd say that hidden_layers for the getter is more descriptive.

I have a vague memory the implementation is a bit more complicated here. If I'm not mistaken there is a list of layers and an additional boolean value telling whether these are specified to be shown or to be hidden. I can't remember where I have seen this though and it could be a misunderstanding.

**Comment by Eneroth3** [comment]
Found it!
Each Layer has a property saying what default state it has for scenes, and scenes have a list of layers that differ from their default setting. Quite convoluted.

https://ruby.sketchup.com/Sketchup/Layer.html#page_behavior-instance_method

**Comment by DanRathbun** [comment]
(Note, I opened a separate issue as this one is about setting for entities - **Please** move your comments to that issue.)

@thomthom [`Page#hidden_entities`](http://ruby.sketchup.com/Sketchup/Page.html#hidden_entities-instance_method) says it returns an Entities object ? How can this be true? `Drawingelement` objects marked as hidden could be in different entities contexts.
Does it really return an array ?

A workaround for setting scene page entity visibilities is "hacky" as the user would see temporary view changes.

Global scene transitions and delay values temporarily saved.
Scene transitions and delay temporarily switched off.
Switch to the scene page to be modified (using a temporary frame change observer, as https://github.com/SketchUp/api-issue-tracker/issues/237 is not yet implemented.)
When transition is complete, changes to the entities visibilities done, and an update to the page.
However a switch back to the previous would want to be done after page update, but the request for a [`onPageUpdate`](https://github.com/SketchUp/api-issue-tracker/issues/26) callback has not yet been implemented. ( A hacky wait timer? )
One benefit may be that the transition back to the previous scene _should_ automatically reset it's entity visibility states.
Global scene transitions and delay values restored.

**Comment by Eneroth3** [comment]
> @thomthom Page#hidden_entities says it returns an Entities object ? How can this be true? Drawingelement objects marked as hidden could be in different entities contexts.
Does it really return an array ?

The entities being in different context should to my understanding not matter. Each entity only has one visibility state in each scene, so the scene can store just a flat array.

**Comment by DanRathbun** [comment]
I know ... but the doc says the method returns an "Entities" object which implies a [`Sketchup::Entities` ](http://ruby.sketchup.com/Sketchup/Entities.html) collection object, which **is itself _normally_ a single context**. 

So it **does** matter what the method return object class is, so the documentation is correct.
(I'm not asking about how the scene object stores state internally. I'm asking for a clarification of what data **class** the method returns about what the scene object has stored.)

**Comment by Eneroth3** [comment]
Oh, now I see it. That appears to be a documentation error. Probably one person just wrote "entities", meaning an array of entity objects, and then someone else (or the same person at a later time) "clarified" it.

`Sketchup.active_model.pages.first.hidden_entities.class #=> Array`

**Comment by thomthom** [comment]
Yup - documentation bug. It returns an array of drawing elements.

**Comment by DanRathbun** [comment]
Thanks for checking. Filed a separate doc issue for the method: https://github.com/SketchUp/api-issue-tracker/issues/381

**Comment by thomthom** [comment]
Logged as SKOR-12271
