### ISSUE TITLE
Directory returned by Sketchup.temp_dir (Windows)

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#410]
In principle, the method **Sketchup.temp_dir**, introduced in Sketchup 2014, would return

_**C:\Users\<username>\AppData\Local\Temp**_

However, some user, at least one on Windows10 (64) has a strange situation where the returns **C:\Temp**, even if the Environment variables for LOCALAPPDATA and APPDATA are defined and point to _C:\Users\<username>\AppData\Local_ and _C:\Users\<username>\AppData\Roaming_.

See [this post](https://sketchucation.com/forums/viewtopic.php?f=51&t=71948&view=unread&sid=956308e0e099e7bb284e663d0fe8b089#p655779).

QUESTION: **Is there any rule about the method Sketchup.temp_dir?**

**Note**: the initial idea was to obtain a clean path to LOCALAPPDATA directory, well translated to UTF. Relying on ENV["LOCALAPPDATA"] is difficult, especially as
  - there are cases where it is not defined
  - it's always complicated to make it a UTF string whenever there are non-ascii characters in the Windows username.

**Comment by MSP-Greg** [comment]
I suspect it does not return what you've shown, as those are defaults.

Probably something similar to:
```ruby
ENV['TMPDIR'] || ENV['TMP'] || ENV['TEMP']
```

Ruby code for tmpdir https://github.com/ruby/ruby/blob/master/lib/tmpdir.rb#L21-L34

Older Ruby versions on Windows had issues, since 2.4 or 2.5 things are much better. But:

1. I've seen the environment variables use a short 8.3 name.

2. Spaces in <username> also may cause issues with older Rubies, I've seen tests get mixed up by it, but I normally install gems with `--user-install`, and my standard <username> has a space, and not problems.

3. Encoding issues.  Also have users check `ENV['RUBYOPT']`, which can be set by Windows Ruby installation proggrams...

**Comment by Fredosixx** [comment]
I got confirmation that Sketchup.temp_dir relies on ENV variables like ENV["TEMP"] and ENV["TMP"].

I believe that SketchUp can manage in C the location of temporary and root data directories without relying on ENV variables (which can be changed by users).

REQUEST: Sketchup should provide solid methods to
  - point to a valid, writable directory for temporary files
  - point to a valid, writable root directory for data file
  - make sure that the returned path are correctly encoded in UTF, even if the Windows username contains non-ascii characters.

This will avoid that _every_ author develop code to get these directories, including management of UTF conversion, and cases where ENV variables are not set, etc....

**Comment by thomthom** [comment]
If the user set TEMP or TMP then that's an indication the user wants temp files to be in that location. Some users might do that due to disk space concern. Not sure what else you'd expect to be used if the system has been told to use a non-standard location.

> make sure that the returned path are correctly encoded in UTF, even if the Windows username contains non-ascii characters.

This has been a Ruby issue that `ENV` data's encoding label has been wrong. Something that needs to be fixed in Ruby, but Ruby has been hesitant to fix due to compatibility concerns.

If the user's machine has been configured to use `C:/temp` - why would you not want to use that?

**Comment by MSP-Greg** [comment]
I checked last night, and TMP is checked first, then TEMP.  There is no check for whether the folder exists.

Part of the mess with encoding is Windows defaults, but it also involves RUBYOPT, and the encoding of the console window that Ruby is running in.  Actions CI uses a different encoding (non standard compared to desktops) than AppVeyor, and some CI tests broke...

**Comment by thomthom** [comment]
On Windows SketchUp is asking the system for the temp path using `GetTempPath`: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppathw

> The GetTempPath function checks for the existence of environment variables in the following order and uses the first path found:
> 
> The path specified by the TMP environment variable.
> The path specified by the TEMP environment variable.
> The path specified by the USERPROFILE environment variable.
> The Windows directory.
> Note that the function does not verify that the path exists, nor does it test to see if the current process has any kind of access rights to the path. The GetTempPath function returns the properly formatted string that specifies the fully qualified path based on the environment variable search order as previously specified. The application should verify the existence of the path and adequate access rights to the path prior to any use for file I/O operations.
> Symbolic link behavior—If the path points to a symbolic link, the temp path name maintains any symbolic links.
> 
> In Windows 8 and Windows Server 2012, this function is supported by the following technologies.

Returning something other than what the system tells us for `Sketchup.temp_path` doesn't seem appropriate to me...

**Comment by Fredosixx** [comment]
Let me rewind....

All extensions having to store data need to a root folder to do so, whether temporray or persistent.

We face 2 problems:
  - Fragility of ENV variables
  - problem of UTF encoding

So we are expecting a set of solid methods from the Sketchup API in order to avoid all the hacks and uncertainties. After all, Sketchup does know where are LocalAppData and the temporary files.

That's all

Fredo

Note:
I was hoping that Sketchup.temp_dir would be a clean implementation, both for the directory and the UTF encoding. And then use File.dirname(Sketchup.temp_dir) to find the AppData directory.

**Comment by DanRathbun** [comment]
> I was hoping that Sketchup.temp_dir would be a clean implementation, both for the directory and the UTF encoding.

It's clean on my machine ...
```ruby
Sketchup.temp_dir
#=> C:/Users/Dan/AppData/Local/Temp
Sketchup.temp_dir.encoding
#=> UTF-8
```
> So we are expecting a set of solid methods from the Sketchup API in order to avoid all the hacks and uncertainties.

The **most solid** thing you can do is create your own "Fredo6" subfolder of `%AppData%` (`"~/Application Support"` on Mac) and a dedicated "TEMP" subfolder inside that. (Keep in mind your extensions will be responsible for cleaning up that folder. And be aware there will be some users who want temp files elsewhere ... perhaps on a HD instead of their SSD.)

> And then use File.dirname(Sketchup.temp_dir) to find the AppData directory.

What's wrong with `ENV["APPDATA"]` ?
... or `ENV["LOCALAPPDATA"]` ?

(You'll likely say the encoding of the string returned.)

----

But using the Windows Scripting Host shell ...
```ruby
require 'win32ole'

def app_data
  WIN32OLE.new("WScript.Shell").ExpandEnvironmentStrings("%AppData%")
end

def local_app_data
  WIN32OLE.new("WScript.Shell").ExpandEnvironmentStrings("%LocalAppData%")
end
```
Usage:
```ruby
app_data().encoding
#=> UTF-8

# ... whereas ...
ENV["APPDATA"].encoding
#=> Windows-1252
```

There are also likely `Fiddle` calls into the Windows library (`shell32.dll` perhaps?) that can get path strings.

----

You can also use WIN32OLE class to access the Windows Scripting Host and it's [`WshSpecialFolders`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/windows-scripting/9x9e7edx%28v%3dvs.84%29) object for paths to special folders that may be language localized.

----

You can test existence using the Ruby core [`File`](https://ruby-doc.org/core-2.5.5/File.html) class:
```ruby
File.exist?(app_data())
#=> true
```
... or the `Kernel::test` method ...
```ruby
Kernel::test(?d,app_data()) # "?d" means: exists and is directory
#=> true
```

**Comment by Fredosixx** [comment]
Dan,

Your code precisely shows why the Sketchup API should contain a method **Sketchup.appdata_dir**, so that each individual developer does not have to go through all workarounds and nitty-gritty of UTF encoding (and need a Windows OLE .so).

**Thomthom**: I close this current issue #410 and will open a new one, clearer.

**Comment by DanRathbun** [comment]
"win32ole.so" is distributed with Ruby in the standard library. (You do not need nor should you to distribute it with your extensions.
