### ISSUE TITLE
Sketchup::View.draw_text uses all edges color instead of black

### ISSUE THREAD

**Issue by lssoft** [SketchUp/api-issue-tracker#437]
SU2015 and higher both Win and OS X.
According to my observations `view.draw_text` uses a color specified for all edges in a display settings instead of a black color, i.e. in case if `view.drawing_color="black"`, then `view.draw_text` substitues black color with a color for all edges. I'm not even sure it is a bug (maybe it is intended behavior in order to make sure that "logically black" text is readable in case if display style has dark or black background).

---

Edit (thomthom): Document what the default color for `view.draw_text` is.

**Comment by thomthom** [comment]
I remember now what is going on. (Didn't connect the dots yesterday, sorry.)

Yes, SU have used the edge colors for the viewport text. It was however not ideal for many extension purposes. 

In SU2016 we added options to the `view.draw_text` method, one of which let you set the text color: `view.draw_text(point, text, color: 'orange')`

We deliberately didn't make it adhere to the `drawing_color` since existing extensions would then start to display random colours for their text depending on what `drawing_color` was called before `draw_text`.

This option is documented, so I'm not sure what else we can do to clarify this. Ideas?

**Comment by lssoft** [comment]
I think it would be enough to clarify that so called _default_ color (i.e. when optional argument is not used) for a text is a color, which is specified for all edges in a display style settings (currently it is not clearly stated in docs: [https://ruby.sketchup.com/Sketchup/View.html#draw_text-instance_method](https://ruby.sketchup.com/Sketchup/View.html#draw_text-instance_method) or maybe I am missing something?
Example code from docs of an old simple way to call `#draw_text(point, text)`
```
    # This works in all SketchUp versions and draws the text using the
    # default font, color and size.
    point = Geom::Point3d.new(200, 100, 0)
    view.draw_text(point, "This is a test")
```

**Comment by thomthom** [comment]
That's a good point. I'll tag this as a documentation issue.

**Comment by Eneroth3** [comment]
Btw, what the UI exposes as the "All Same" (Edge) color is called simply Color as rendering option. It is also used for preview lines in multiple native tools and can be thought of as the model's default line color.
