### ISSUE TITLE
SUArcCurveCreate() modifies endpoints for a closed circle

### ISSUE THREAD

**Issue by MylSh** [SketchUp/api-issue-tracker#44]
SketchUp Version: API Version 5.0 - SketchUp 2017
Windows 10 x64

I'm attempting to use SUArcCurveCreate to create a circle.  Querying the endpoint of the ArcCurve immediately after creation shows that it is different than what was specified.

```c
   SUPoint3D startPt = {11, 0, 0};
   SUPoint3D centerPt = {0, 0, 0};
   SUPoint3D endPt = {11, 0, 0};
   SUVector3D normal = {0, 0, 1};
   const size_t num_edges = 92;

   SUArcCurveRef arcCurve = SU_INVALID;
   SUResult res = SUArcCurveCreate(&arcCurve, 
                                   &centerPt, &startPt, &endPt, &normal, num_edges);
   // SU_ERROR_NONE == res

   bool isFullCircle;
   res = SUArcCurveGetIsFullCircle( arcCurve, &isFullCircle);
   // (SU_ERROR_NONE == res) &&  (true == isFullCircle)

   res = SUArcCurveGetStartPoint(arcCurve, &startPt);
   // (SU_ERROR_NONE == res) && ((11,0,0) == startPt)
   
   res = SUArcCurveGetEndPoint(arcCurve, &endPt);
   // (SU_ERROR_NONE == res) && ((11,-2.6942229581241772e-15,0) == endPt)
```

The expected result was to have an arcCurve that represents a full circle, and whose start and end points are both `(11,0,0)`.

**Comment by DanRathbun** [comment]
Likely because of the weird number of segments you chose.

SketchUp really needs an even number of segments per quadrant, so that cardinal points fall on the axis and midway between.

You'll get the same kind of weird circles via the manual GUI if you use strange numbers of segments.

The best choices are those that equally divide by all of: **`2`**, **`3`** and **`4`**. 
Such as **`96`**, **`48`**, **`36`**, etc.

**Comment by thomthom** [comment]
`-2.6942229581241772e-15` is near null value. This is floating point precision noise one need to account for. 
In the SU2018 SDK we added functions for equality with tolerance. Even for Point3d/Vector3ds, which is more appropriate to use in this case since we're dealing with point3d objects.

As a demonstration, if you feed these coordinates to `Geom::Point3d` in the Ruby API you see how they are compared with tolerance:

```ruby
pt1 = Geom::Point3d.new(11,0,0)
# => (279,4mm, 0mm, 0mm)
pt2 = Geom::Point3d.new(11,-2.6942229581241772e-15,0)
# => (279,4mm, -0mm, 0mm)
pt1 == pt2
# => true
```

**Comment by MylSh** [comment]
Thanks!  Until those equality operators come around, would it be correct to assume that SketchUp is using a tolerance of 1/1000" ( https://forums.sketchup.com/t/is-tolerance-for-vector3d-documented-anywhere/5443)?

Internally, does sketchup use 3D distance for equality comparisons, and is it a strictly-less-than comparison, or a less-than-or-equal-to comparison?

**Comment by DanRathbun** [comment]
> Until those equality operators come around ...

"Come around" ? They've been deployed in v 6.0 (2018). You can get them now.
If you are targeting v2017 SKP files, then you can use v6.0 and backsave as SKP v2017.

> ... would it be correct to assume that SketchUp is using a tolerance of `1/1000"`

We DO say this generally. But it does not translate exactly to the orthographic coordinate values. (See link below to another issue thread.)

The Documentation used to give the number, but I think it was removed (as it is considered an "implementation detail" that they may wish to change in the future. Perhaps getting more precise?)

We've discussed this here in [issue 15.](https://github.com/SketchUp/api-issue-tracker/issues/15)
Please read [this issue](https://github.com/SketchUp/api-issue-tracker/issues/15) in it's entirety.
(The "forum search" mentioned refers to the main [public forum](https://forums.sketchup.com).)

> Internally, does SketchUp use 3D distance for equality comparisons, and is it a strictly-less-than comparison, or a less-than-or-equal-to comparison?

I can't say what is done internally (not having seen the code.)

It's generally a "within" tolerance comparison. To mimic this in our own code, each coordinate component must be checked against the other point (or vector's) complimentary coordinate. If the absolute **difference** between the two is "within" the tolerance then they are the same coordinate. But if they are exactly far enough **different**, then no they are different coordinates. 

The equal-to would prove the coordinates are different, IF (and only IF) you use the "magic number" for comparison. IF that magic number is `0.001`, then only **less-than** would prove that the coordinates are the same.

I cannot see you wanting to use some crazy `9.999999999999e-4` as the magic number in order to do a less-than-or-equal-to comparison. Dealing with a nice rational number (`0.001`) would be better I'd think.

**Comment by DanRathbun** [comment]
@thomthom Why tag as a "**bug**" when it is not ? 
Perhaps we need an "**expected behavior**" / "**as designed**" tag ?

**Comment by thomthom** [comment]
> Internally, does SketchUp use 3D distance for equality comparisons, and is it a strictly-less-than comparison, or a less-than-or-equal-to comparison?

Use the equality functions in the SU2018 SDK instead of implementing your own - it'll be future-proof.

**Comment by thomthom** [comment]
> @thomthom Why tag as a "bug" when it is not ?
It was reported as a bug. Had I not been able to verify this before logging in the internal tracker that's how it would have been logged.

I wasn't use whether to use the `wont-fix` or `invalid` tag, or create a new one. But ended up not spending too much time on it.

**Comment by MylSh** [comment]
Thank you!  I was unable to find reference to the new equality methods through the ["Data Structures" portion of the API site](http://extensions.sketchup.com/developer_center/sketchup_c_api/sketchup/annotated.html), so assumed they were still in the works.  Accessing through the ["Files" section](http://extensions.sketchup.com/developer_center/sketchup_c_api/sketchup/point3d_8h.html#aaf2f9de1edb8915dd22d90c7b386ea5b) shows the new equality operators are in place.  I'll update my library and use the future-proof versions.
