### ISSUE TITLE
#active_path documentation contradiction

### ISSUE THREAD

**Issue by mariocha** [SketchUp/api-issue-tracker#455]
1. SketchUp/LayOut Version: Pro 2020
2. OS Platform: all

Excerpt:

> The [#active_path=] method is used to open a given instance path for editing.
> It is expected that no entities are modified in an operation that opens/closes instances.

open for edit but do not modify !

**Comment by thomthom** [comment]
hm... I guess that can be confusing.

The next paragraphs provides more information though. I shows that SU will break apart Ruby Operations into chained operations to ensure entities are not edited in the same operation the active context is changed.

The documentation mentions this because it has an effect on the operation (transaction) notifications being sent.

**Comment by DanRathbun** [comment]
Shouldn't the second call to add a face (in the code example) be done against `.active_entities` so the example makes sense ?

**Comment by DanRathbun** [comment]
Also the grammar for the 1st sentence of the note is a bit confusing ...
> _Note: Since changing the active entities in SketchUp also changes what coordinate system is used, entities can't be modified in the same operation **as the active entities changes**. _

IMO, it would be better said as ...

"**Note**: Since changing the active entities in SketchUp also changes what coordinate system is used, entities can't be modified in the same operation as the active entities are changed."
