### ISSUE TITLE
Sketchup::Page#update referencing magic numbers instead of constants

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#469]
https://ruby.sketchup.com/Sketchup/Page.html#update-instance_method

The method document internal values, which is fragile to rely on.

There are constants for these values which are what should be used, and the documentation and examples should be using these:

https://ruby.sketchup.com/top-level-namespace.html
```
PAGE_USE_CAMERA
PAGE_USE_RENDERING_OPTIONS
PAGE_USE_SHADOWINFO
PAGE_USE_SKETCHCS
PAGE_USE_HIDDEN
PAGE_USE_HIDDEN_GEOMETRY
PAGE_USE_HIDDEN_OBJECTS
PAGE_USE_LAYER_VISIBILITY
PAGE_USE_SECTION_PLANES
PAGE_USE_ALL 
```

**Comment by DanRathbun** [comment]
> They are hidden in the list of top level constants;

I wish they'd be redefined thus ...

```ruby
Sketchup::Page::USE_CAMERA ||= PAGE_USE_CAMERA
Sketchup::Page::USE_RENDERING_OPTIONS ||= PAGE_USE_RENDERING_OPTIONS
Sketchup::Page::USE_SHADOWINFO ||= PAGE_USE_SHADOWINFO
Sketchup::Page::USE_SKETCHCS ||= PAGE_USE_SKETCHCS
Sketchup::Page::USE_HIDDEN ||= PAGE_USE_HIDDEN
Sketchup::Page::USE_HIDDEN_GEOMETRY ||= PAGE_USE_HIDDEN_GEOMETRY
Sketchup::Page::USE_HIDDEN_OBJECTS ||= PAGE_USE_HIDDEN_OBJECTS
Sketchup::Page::USE_LAYER_VISIBILITY ||= PAGE_USE_LAYER_VISIBILITY
Sketchup::Page::USE_SECTION_PLANES ||= PAGE_USE_SECTION_PLANES
Sketchup::Page::USE_ALL ||= PAGE_USE_ALL
```

Or the other way 'round. Redefined in the class, and then aliased at the toplevel for backward compatibility.

Although I show removing the `"PAGE_"` prefix it's not totally necessary especially if the following is done ...

----

A common pattern is to have class specific constants in a mixin submodule of the class, and mix it into the class proper, and then it also allows them to be mixed into SketchUp extension modules.

A **major** benefit of the constant submodule pattern is that these mixin modules can be frozen preventing inadvertent changing of their constants (by uninformed newbs) that could affect many other extensions.

:?:

**Comment by DanRathbun** [comment]
The documentation also does not show that the argument is optional, and what happens when `#update` is called **without** an argument.

In a [reply](https://forums.sketchup.com/t/ruby-bug-or-documentation-correction-su-2020-1-page-update-16-vs-page-update-384/124424/8) to a coder asking whether they could assume that it updated everything, .. I answered ...

> **EDIT**: You are semi-correct ... the answer is **_KIND OF_**.
> 
> A good lesson in not assuming things. A page object has update flags.
> There are setters for these flags, such as [`#use_camera=`](https://ruby.sketchup.com/Sketchup/Page.html#use_camera=-instance_method),
> ... and boolean getters, such as [`#use_camera?`](https://ruby.sketchup.com/Sketchup/Page.html#use_camera%3F-instance_method).
> 
> The [`#update`](https://ruby.sketchup.com/Sketchup/Page.html#update-instance_method) method lets you update a scene page targeting specific flags **as those flags are set**.
> 
> But if you call [`#update`](https://ruby.sketchup.com/Sketchup/Page.html#update-instance_method) without a numeric argument, then **all** the flags **as set** (ie, as you see them checked in the Scenes inspector) for that scene page, will be used.
> 
> This can be a bit confusing (as it just confused me.) If the `#use_camera?` flag is set `false` by unchecking the "Camera Location" box in the Scenes inspector, then no amount of calling `page.update(1)` will update the camera location for that scene.

This confused me as I always thought that `#update` would do what I told it to do regardless of what the update flags were set to do (for manual scene updating.) I do remember things not working exactly as I meant in the past but didn't put 2+2 together.

So, really the description of **what** the `#update` method does, ... is not enough to say that "_Which parts of the Page get updated are controlled via an integer whose bits represent which parts to update_", because it's **not entirely true** and is **misleading**.
The numeric arguments **really** tell SketchUp which instance flags (as they are set) to use when updating.

Now I have to think about wrapper **override** methods that DO update what I want updated.
