### ISSUE TITLE
HtmlDialog: No method set_background_color, No method get_element_value

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#491]
I am in the process of migrating to HtmlDialog. As I have a wrapper, I have almost no issue with the HTML / Javascript part, and I am testing a few other aspects.

I realize that there is NO method: ```set_background_color```.

Is this intentional?

I guess I can manage this with CSS from within the HTML, but just curious.

For ```get_value```, I wonder why this has not been carried over from UI::WebDialog.

**REQUEST**: Not sure these are formal requests yet. Just trying to understand.

**Comment by DanRathbun** [comment]
> For `get_value`, I wonder why this has not been carried over from UI::WebDialog.

Because it was "fake". It just returns a hard-coded color value for the default Windows system dialog background color. Ie, you an call it even before a web dialog is opened, so it doesn't actually retrieve the _real_ page's background color.

----
POSSIBLE WORKAROUND:

```ruby
# Define singleton callback:

wd.add_action_callback("store_background_color") { |_unused, color_str|
  wd.instance_variable_set(:@background_color, Sketchup::Color.new(color_str))
}

# Define singleton methods:

def wd.background_color
  @background_color
end

def wd.get_background_color
  # Asynchronous get from Ruby ...
  wd.execute_script(
    %[sketchup.store_background_color( document.body.style.backgroundColor );]
  )  
end

def wd.set_background_color(color_str)
  color_str = '#'+color_str if color_str[0,1] != '#'
  @background_color = Sketchup::Color.new(color_str)
  wd.execute_script(
    %[document.body.style.backgroundColor = "#{color_str}";]
  )  
end
```
 > Is this intentional?

Probably was left out of the `UI::HtmlDialog` class because the the asynchronous nature of the CEF communications.

You'll note in the example above that the `wd.get_background_color()` singleton method cannot **immediately** return the color value. It must be returned asynchronously via a callback that stores it in an instance variable. You'll then (after having given enough time) need to read the `@background_color` variable using a normal getter (as also shown above.)

**Comment by Fredosixx** [comment]
Actually my request was only for
  - ```set_background_color```
  - ```get_element_value``` (which returns the value of an HTML element, in particular input fields)

I did not know (or use) ```get_background_color```.

**Comment by Eneroth3** [comment]
You don't need to set the window background color from Ruby; you can use CSS and set it from where you set all other styling. The CSS3 draft had "keywords" for system colors like button and text colors. I think it was removed before the final specification, but browser engines seem to support it quite well anyway.

For field values I typically make the submit button call a JS function in the dialog that collects all values and pass them as parameters to the callback. The ability to pass data along with the callback has been hugely improved in HTMLDialogs and supports various data types, not just strings.

**Comment by Fredosixx** [comment]
I know (and said) we can do without. I was just curious to hear why it was not included in HtmlDialog (at least to make the migration easier).

For ```element_get_value```, I use it in one occurrence in all my plugins. For whatever reason, when called in the ```onChange``` event, it gives the value before the change takes place. I drive all my dialogs from Ruby, not from Javascript, so it may be convenient.

HtmlDialog seems to have improve the Mac side of things (no lost messages in transmission) but has introduced issues on the Windows platform, in particular with severe differences between SU2017 and all subsequent versions of Sketchup. 

And HtmlDialog did not solve the flaws of WebDialog concerning the dialog sizing, nor the problem of focus management, which were the number one problems limiting the usage of web-based dialog for driving an interactive UI. Again, it's a pity no developer was consulted at the time HtmlDialog were designed....

**Comment by DanRathbun** [comment]
> The CSS3 draft had "keywords" for system colors like button and text colors. I think it was removed before the final specification, but browser engines seem to support it quite well anyway.

It was actually CSS 2.1 (3 has proposed to deprecate their use, which I think is dumb.)
* https://www.w3.org/TR/CSS21/ui.html#system-colors
* https://www.w3.org/TR/CSS2/fonts.html#font-shorthand

> Actually my request was only for ...

No You've since changed the topic title, and specifically mused why "get_value" wasn't carried over. Since you were first asking about **setting the background color**, it was appropriate for me to assume you also meant getting the background color value.

**But it doesn't matter** ...

> For `element_get_value`, I use it in one occurrence in all my plugins. For whatever reason, when called in the `onChange` event, it gives the value before the change takes place. I drive all my dialogs from Ruby, not from Javascript, so it may be convenient.

... **because the reason is the same, as I said, the CEF framework is asynchronous and cannot return immediate values**.

So the example I give above is valid for returning any kind of HTML element value or JS variable value. Ie, the Ruby-side must make an asynchronous "request" to the JS-side. Later when the CEF is ready to, it will send the value to a callback whose block can respond to the value in some way.

> And HtmlDialog did not solve the flaws of WebDialog concerning the dialog sizing, ...

I'll respond to this in your issue #492.

> ... nor the problem of focus management, ...

**Agree**. We still have this open issue. (I hate the ugly hacks we must perform.)

* [Issue 430 : **REQ: UI::HtmlDialog#set_on_focus and UI::HtmlDialog#set_on_blur block form methods**](https://github.com/SketchUp/api-issue-tracker/issues/430)

Even a simple **`Sketchup::app_focus`** module method would **really** help.

**Comment by Eneroth3** [comment]
If HtmlDialogs had the exact same functionality, there would be no need to make it a separate class in the first place, it could just have been an update to WebDialogs. Since the devs started fresh there can be changes, both for purely technical reasons as Dan has described and for API design reasons. It gives a higher cost for migrating existing code, but lower the cost of using the new API for new projects.

Regarding the method for setting the background color, I also missed it when it disappeared and I was used to use it, but thinking of it the method didn't make that much sense. All other visual appearance (font face, text size, text color) is set inside the HTML Dialog using conventional web methods. It just makes sense to keep this contained into one place.

Regarding focus management and sizing, I don't think everything is lost. By writing clear feature requests and having several users filling in why we need it and for what, I suspect new API can be added fairly quickly. This is not about an underlying design flaw of the class that could have been avoided if feedback was given earlier, but rather functionality currently missing.

**Comment by Fredosixx** [comment]
> This is not about an underlying design flaw of the class that could have been avoided if feedback was given earlier, but rather functionality currently missing.

Precisely, the feedback on focus issues was given early, long before HtmlDialog came. Actually, it would be good that the API designers at Sketchup use themselves the API in real projects, or ask developers to do it. 

It would take 5 minutes to realize that the stealing of focus by the dialog box is a major problem when trying to drive an interactive UI where you navigate between the dialog and the viewport (especially on Mac where you need to click twice). 

So it's more fundamental than a functionality that can be added 'when time permits'.

**Comment by Fredosixx** [comment]
I suggest we close this issues, as we can do without it.

In the end, there is no particular request.

**Comment by thomthom** [comment]
Regarding the `UI::HtmlDialog` and `UI::WebDialog` interface differences. 

Dan captured the gist of it in his comment earlier: https://github.com/SketchUp/api-issue-tracker/issues/491#issuecomment-638812624

When we started to implement `UI::HtmlDialog` we set out with the intention of making it a replacement interface. But because CEF is fundamentally different in being async and in different processes it was impossible to make a 100% 1:1 interface. `UI::WebDialog` behaving different on Windows/macOS was already an issue.

Because of they we let the interfaces diverge, shaping it after least path of resistance to how CEF worked instead of trying to partially emulate `UI::WebDialog`.

As for the other issues requests for `UI::WebDialog`/`UI::HtmlDialog`, and anything else really - it's been a issue of available developer time vs  amount of work that needs to be done.

A number of the things that has been requested are things we have talked about and wanted to add, but had to draw the line at some point because there simply wasn't time.
