### ISSUE TITLE
Sketchup module method to return focus to the modeling window

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#493]
#### SketchUp Live API Feature Request (C and Ruby)

`Sketchup` module method to return focus to the modeling window.

This has already been requested for like 10 years or more. And we still do not have it!
I'm opening this as a public issue so other coders can add their comments.

We should not need to do dirty hacks like opening a tiny temporary webdialog off screen and then closing it, in order to return input focus back to the application window from a **non-modal** child window such as a web dialog.

----

_REF SKETCHUP FORUM TOPICS:_

[How to set Focus to Mainwindow](https://forums.sketchup.com/t/how-to-set-focus-to-mainwindow/12383) (JUN 2015)

[Create HtmlDialog with clickable thumbnails](https://forums.sketchup.com/t/create-htmldialog-with-clickable-thumbnails/47113) (JUN 2017)

[Focus event on window object from CEF HtmlDialog Javascript?](https://forums.sketchup.com/t/focus-event-on-window-object-from-cef-htmldialog-javascript/115945) (FEB 2020)

[How to access existing toolbars and call existing commands?](https://forums.sketchup.com/t/how-to-access-existing-toolbars-and-call-existing-commands/119388) (MAR 2020)

[Can HtmlDialog yield focus to SketchUp view?](https://forums.sketchup.com/t/can-htmldialog-yield-focus-to-sketchup-view/123696) (APR 2020)

----

_REF SKETCHUCATION FORUM TOPICS:_

[Shift WebDialog Focus to SU?](http://sketchucation.com/forums/viewtopic.php?f=180&t=19167) (MAY 2009)

[X-Mouse Window Focus for Mac OSX ??](http://sketchucation.com/forums/viewtopic.php?f=180&t=33715) (DEC 2010)

[Losing focus on window](http://sketchucation.com/forums/viewtopic.php?f=180&t=48779) (NOV 2012)

**Comment by Fredosixx** [comment]
**I vote for this request**. 

Very important, because when the focus is on a dialog box, and the modeling window is under and interactive tool (```Sketchup::Tool```) you do no get the scrolling events, nor the tooltip displaying.

On Mac this is even worse, because you need to click first on the viewport to activate it before doing anything, and this click is a 'wasted' event.

By the way, 
1. **the hack of opening briefly a dummy dialog box does NOT work on Mac**. Instead, it gives back focus to the dialog which had the focus before. 
2. the hack with WinOLE works fine on Windows (thanks Dan)
3. On Mac, there is no way to emulate the requested app_focus with Applescript, because any script executed from the Sketchup process is prevented to act on the Sketchup process (it would work fine from the script editor however). So there is NO hack for Mac.

**Comment by DanRathbun** [comment]
Yeah! Hurrah! Yeepeeee!
