### ISSUE TITLE
Please fix Doxygen warnings in some of the SketchUp SDK headers

### ISSUE THREAD

**Issue by jgmaxon** [SketchUp/api-issue-tracker#498]
# Bug Reports

1. SketchUp/LayOut Version: 2020.1 C SDK
2. OS Platform: Windows and macOS

Please fix the following Doxygen warnings in the C API headers, we can’t do so on our side without breaking the macOS signature on the SDK's framework.  ~~Please note that I had to put a space between the @ symbol and the word 'since', as otherwise it creates an unwanted and unrelated link to a github user's name.~~

**First Issue**

In edge.h, add the @ since between the following lines:
```
@brief Computes the length of the edge with the provided transformation applied.
@since 
@param[in]  edge      The edge object.
```
**Second Issue**

In component_definition.h, and an extra / to make it three in a row on the following lines:
```
enum SUComponentType {
  SUComponentType_Normal,  ///< Regular component definition
  SUComponentType_Group    ///< Group definition
};
```

Thanks,

Joey

**Comment by DanRathbun** [comment]
> Please note that I had to put a space between the @ symbol and the word 'since', as otherwise it creates an unwanted and unrelated link to a github user's name.

Use GitHub flavoured [**markdown**](https://guides.github.com/features/mastering-markdown/) to mark these words as code (using sible backquote delimiters) `@since`, `@brief` and `@param` when used alone in a sentence, or as a code block using ` ```c` (as an opening line delimiter, and ` ``` ` (as a closing line delimiter,) ie ...
```c
@brief Computes the length of the edge with the provided transformation applied.
@since 5.0
@param[in] edge The edge object.
```
Yes even when typing into code blocks the silly web interface wants to suggest user accounts after an `@`, so just press the ESC key so dismiss the account suggestion popup list. 

When the code words or blocks are rendered they will **not** be linked to an account.

When you are editing / adding a post, there is always a quick link to the markdown primer at the bottom right, below the edit box. (An M with a down arrow button.) It's just above the "Comment" button.

----

Your first issue is referring to the declaration for the `SUEdgeGetLengthWithTransform` function.
I see the line you speak of in the all C SDK `"edge.h"` files (beginning with API ver 5.0, rel 2017 M0) but it has never had a value. 
**Is this what is causing the doxygen warning?**

Your second issue refers to the enumeration declaration beginning on lines 78 of `"component_definition.h"` which (as you say) should be ...
```c
enum SUComponentType {
  SUComponentType_Normal,  ///< Regular component definition
  SUComponentType_Group    ///< Group definition
};
```

----

P.S. - Your reports do not need to _parrot_ the "**API Isssue Only**" warning section. (That was for your consumption only as the author of an issue.)

**Comment by jgmaxon** [comment]
Hi Dan,

Thanks for the tips, as you can see, I edited my post accordingly.  I'm actually just suggesting fixes to the doxygen that work, but if a more appropriate change can be made to eliminate the warnings, then that's fine too.

Cheers,

Joey

**Comment by thomthom** [comment]
We got a number of Doxygen fixes to the C API docs - should be 0 errors/warnings when they are released.

Are you running Doxygen on the SDK headers? Can I ask why?

**Comment by jgmaxon** [comment]
Hi,

Thanks for fixing the Doxygen warnings!  I integrated the SketchUp 2020.2 SDK into our codebase and all the warnings are gone.  This helps us a lot, as it was affecting our macOS build warning list on our build machine.  XCode is set up to check for Doxygen warnings in the source code at build time and displays any found.  Our SDK docs are created with Doxygen and posted online, so although we don't post Doxygen from 3rd party SDKs, they aren't excluded from analysis.  Since I'll admit I don't know all the details, if that's not totally accurate, the real explanation is likely close.

In any case, it's really appreciated, as we're going to set warnings to be treated like errors for our builds sooner or later, and I didn't want to suppress the Doxygen warnings.

Cheers,

Joey

**Comment by DanRathbun** [comment]
> Since I'll admit I don't know all the details, if that's not totally accurate, the real explanation is likely close.

LOL "_Stay thirsty, my friends!_"
