### ISSUE TITLE
Ruby gsub and non-ascii character

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#577]
Not in the Sketchup API itself, but worth noting as this is in Ruby.

I have a Korean user who has setup his Windows machine with a Korean username.

Now, we have the following situation, when trying to swap the backslash to a forward slash in a path coming from `ENV["LOCALAPPDATA"]`.

**1) `gsub` with regular expression**

`ENV["LOCALAPPDATA"].dup.force_encoding("UTF-8").gsub(/\\/, "/")`

Error: #<ArgumentError: invalid byte sequence in UTF-8>
<main>:in 'gsub'
<main>:in '<main>'
SketchUp:1:in 'eval'

**2) `gsub` with string**

`ENV["LOCALAPPDATA"].dup.force_encoding("UTF-8").gsub("\\", "/")`
C:/Users/￈ﾫ﾿￬ﾺ￳/AppData/Local

For whatever reason, gsub with regular expression does not like too much the Korean characters, even if they appear do be in UTF8.

Is anybody aware of the problem?

**Comment by Eneroth3** [comment]
In the future I'd say this is a better discussion for the SketchUp forum, as it is technically isn't related to the API.

When testing this on my machine `ENV["LOCALAPPDATA"].encoding` it says the encoding is "Windows-1252".

I'd try to swap out `force_encoding` with `encode`. `force_encoding` doesn't translate the string content to the new encoding, only changes what encoding the string is "tagged" with. Generally `force_encoding` shouldn't be used, but when an API returns a String that is incorrectly tagged as having another encoding than what was used for the string content, it is useful.

**Comment by Fredosixx** [comment]
Not related to Sketchup API

**Comment by DanRathbun** [comment]
Generally you should use:
```ruby
path_string.gsub(/\\\\|\\/, '/')
```
... because some API methods return path strings on Windows platform with double backslashes, other methods with single backslashes. So you want to change double backslashes to a single forward slash before you treat single backslashes. (Otherwise you run the risk of getting double forward slashes.

**Comment by Eneroth3** [comment]
I can't remember seeing any double backslashes returned by the API. Could you be seeing the escape character added for displaying a single backlash within double quotes?

`ruby
string = 'only\single\backslashes\here'
puts string
# "only\\single\\backslashes\\here"
`

**Comment by DanRathbun** [comment]
(Your example is invalid. The string is displayed with single backslashes.
However, calling [`String#inspect`](https://ruby-doc.org/core-2.5.5/String.html#method-i-inspect) on a string will escape internal backslash characters.)

I do remember this happening. Perhaps it was from using `#inspect`. A look at the JSON preference files shows most paths are using escaped backslashes rather than forward slashes on Windows.

----

I thought it was either [`Sketchup::find_support_file`](https://ruby.sketchup.com/Sketchup.html#find_support_file-class_method), [`Sketchup::find_support_files`](https://ruby.sketchup.com/Sketchup.html#find_support_files-class_method) or [`Sketchup::get_resource_path`](https://ruby.sketchup.com/Sketchup.html#get_resource_path-class_method), but they seem to be returning forward slash pathnames in SU2020.

FYI, the following still return pathnames with backslashes (on Windows) instead of forward slashes:

* [`Sketchup::Model#path`](https://ruby.sketchup.com/Sketchup/Model.html#path-instance_method)
* [`Sketchup::ComponentDefinition#path`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html#path-instance_method)
`This actually returned a path with forward slashes in SU2016 for the Lisanne component.`
* [`Sketchup::Image#path`](https://ruby.sketchup.com/Sketchup/Image.html#path-instance_method)
* [`Sketchup::Texture#filename`](https://ruby.sketchup.com/Sketchup/Texture.html#filename-instance_method)

The following returned pathnames with backslashes in previous versions:
* [`Sketchup::template`](https://ruby.sketchup.com/Sketchup.html#template-class_method)

----

The following **getter methods** are returning pathnames with forward slashes:
* [`LanguageHandler#resource_path`](https://ruby.sketchup.com/LanguageHandler.html#resource_path-instance_method)
* [`Sketchup::find_support_file`](https://ruby.sketchup.com/Sketchup.html#find_support_file-class_method)
* [`Sketchup::find_support_files`](https://ruby.sketchup.com/Sketchup.html#find_support_files-class_method)
* [`Sketchup::get_resource_path`](https://ruby.sketchup.com/Sketchup.html#get_resource_path-class_method)
* [`Sketchup::temp_dir`](https://ruby.sketchup.com/Sketchup.html#temp_dir-class_method)
* [`Sketchup::template_dir`](https://ruby.sketchup.com/Sketchup.html#template_dir-class_method)
* [`SketchupExtension#extension_path`](https://ruby.sketchup.com/SketchupExtension.html#extension_path-instance_method)
* [`UI::Command#large_icon`](https://ruby.sketchup.com/UI/Command.html#large_icon-instance_method)
* [`UI::Command#small_icon`](https://ruby.sketchup.com/UI/Command.html#small_icon-instance_method)

**BUT**, I am **unsure** whether these getter methods are doing anything with the slashes. They may just be returning the pathname as it was set, so it may be the setters that are the culprits. Ie, **what I remember** may have been a situation in the past where a setter method or constructor was passed a path with escaped backslashes and it was saved internally this way, and so returned by a getter this way..

~

**Comment by thomthom** [comment]
> For whatever reason, gsub with regular expression does not like too much the Korean characters, even if they appear do be in UTF8.
> 
> Is anybody aware of the problem?

The `ENV` variables (as well as `__FILE__` and `__dir__`) has always been problematic on Windows in terms of encoding. I reported it to Ruby a while back (or found some existing issue) and it was said that they were hesitant to change it in case it would break existing applications. It might be addressed in Ruby 3 since it's a major version update.

I'm a little surprised however that `dup.force_encoding` doesn't work here if the string is really UTF-8.

Can you do a byte dump of the string and report it back here? `ENV["LOCALAPPDATA"].bytes`

**Comment by thomthom** [comment]
> I'd try to swap out force_encoding with encode. force_encoding doesn't translate the string content to the new encoding, only changes what encoding the string is "tagged" with. Generally force_encoding shouldn't be used, but when an API returns a String that is incorrectly tagged as having another encoding than what was used for the string content, it is useful.

The issue with `ENV` etc is that the bytes making up the string tend to be UTF-8, but the string object is labelled as having encoding `us-ascii`. In which case `.encode` will not work.

**Comment by DanRathbun** [comment]
On my machine, all the `ENV` strings are system encoded as `Windows-1252`. Is this the same as `us-ascii` ?

**Comment by thomthom** [comment]
No, `us-ascii` is a 7-bit encoding. `Windows-1252` is an 8-bit encoding (sometimes mis-labeled as ANSI) Often it's also confused for `ISO 8859-1` because it's a partical superset.

I was wrong in saying that `ENV` used `us-ascii`, the encoding it gets applied is system dependent. On Windows it'll usually have the encoding marker of the current code page. (But the string data is still UTF-8 in many cases.)

 It's quite the mess...

**Comment by DanRathbun** [comment]
> On my machine, all the **[`ENV`](https://ruby-doc.org/core-2.7.1/ENV.html)** strings are system encoded as Windows-1252.

**I need to take this back.** 

**This WAS true.** But I had not noticed before that with SU2021 and Ruby 2.7.1 that now all the **[`ENV`](https://ruby-doc.org/core-2.7.1/ENV.html)** strings are encoded as `ASCII-8BIT`. **Was this an intentional change ?** (This needs to be noted in the Release Notes.)

Since SketchUp started distributing with Ruby 2.x, I have proposed that you guys should set **[`Encoding.default_internal`](https://ruby-doc.org/core-2.7.1/Encoding.html#method-c-default_internal)** which is supposed to affect **[`ENV`](https://ruby-doc.org/core-2.7.1/ENV.html)** strings. (It also effects **[`Etc.systmpdir`](https://ruby-doc.org/stdlib-2.7.1/libdoc/etc/rdoc/Etc.html#method-c-systmpdir)** among several other things.)
But **[`Encoding.default_internal`](https://ruby-doc.org/core-2.7.1/Encoding.html#method-c-default_internal)** remains unset to this day.

Weirdly, **`__ENCODING__`** **is** set to **UTF-8** for the `ObjectSpace`. (This is normally the encoding set by a file's "magic" encoding comment.) I find it weird that this is set, but not **[`Encoding.default_internal`](https://ruby-doc.org/core-2.7.1/Encoding.html#method-c-default_internal)**.

I've also just been made aware of the **[`Encoding::compatible?`](https://ruby-doc.org/core-2.7.1/Encoding.html#method-c-compatible-3F)** method. I think this method should be used as a test **before** using **[`String#force_encoding`](https://ruby-doc.org/core-2.7.1/String.html#method-i-force_encoding)**.

**Comment by thomthom** [comment]
> Was this an intentional change ? (This needs to be noted in the Release Notes.)

That's not a change on our end. `ENV` etc is entirely handled by the Ruby implementation and not transparent to us.

> Since SketchUp started distributing with Ruby 2.x, I have proposed that you guys should set Encoding::default_internal which is supposed to affect ENV strings.

I don't recall the exact details any more, but I don't think that entirely fixed thing. Might have brought about other issues. Bottom line is that encoding from system variables on Windows in Ruby 2.x is a mess and a pain. Upstream Ruby maintainers are aware but, compatibility. It's more likely that Ruby 3 could provide some relief for this. Haven't had time to test though.

**Comment by DanRathbun** [comment]
> That's not a change on our end. ENV etc is entirely handled by the Ruby implementation and not transparent to us.

I asked because you've just begun compiling SketchUp's Ruby with this release. And we have this change.
(Yea, it could something that changed between 2.5.x and 2.7.x in the Ruby Core. Ie, since all the ENV strings must be 8bit ASCII compatible, the core may have done this instead of having all the deployments on latin localized platforms have ENV encodings with their different (but compatible) encoding classes.

**Comment by MSP-Greg** [comment]
@DanRathbun

> This WAS true. But I had not noticed before that with SU2021 and Ruby 2.7.1 that now all the ENV strings are encoded as ASCII-8BIT

Confused.  On my system
```
ENV.each { |k,v| puts "#{k.encoding}  #{v.encoding}" }
```
returns `Windows-1252` for all keys and values?  Some items I've added, some I've changed values, and some are original.

**Comment by DanRathbun** [comment]
WEIRD !!!

Just did that again and all the encodings are `Windows-1252`.

The other day when I did the same, they were all `ASCII-8BIT`. I am confused even more now.

**Comment by thomthom** [comment]
Yup...
