### ISSUE TITLE
Change Sketchup::Model#active_path use active_entities in @note example

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#602]
https://github.com/SketchUp/api-issue-tracker/issues/455#issuecomment-757021073

This should all use `model.active_entities`:

![image](https://user-images.githubusercontent.com/192418/104168935-18a27d00-53ff-11eb-9007-b6ee0ffde65b.png)

**Comment by DanRathbun** [comment]
Also the grammar for the 1st sentence of the note is a bit confusing ...
> _Note: Since changing the active entities in SketchUp also changes what coordinate system is used, entities can't be modified in the same operation **as the active entities changes**. _

IMO, it would be better said as ...

"**Note**: Since changing the active entities in SketchUp also changes what coordinate system is used, entities can't be modified in the same operation as the active entities are changed."

**Comment by DanRathbun** [comment]
Opened new issue for the **still** confusing grammar in the note:

https://github.com/SketchUp/api-issue-tracker/issues/755
