### ISSUE TITLE
math calculation error

### ISSUE THREAD

**Issue by SoapSkinBubble** [SketchUp/api-issue-tracker#661]
Type in Ruby Console:
4.98 + 35.90
you get:
40.879999999999995

SketchUp 2020 and 2021 
Windows and OS X

**Comment by SoapSkinBubble** [comment]
Type in Ruby Console:
4.98 + 35.90
you get:
40.879999999999995

**Comment by Eneroth3** [comment]
This is an expected behavior. Computer typically use floating point numbers for anything that isn't integers. There is a limit to how precise such number can be.

On top of that is the conversion between decimal and binary numbers. As an analog, if you were to sum up 3.3333333, 3.3333333 and 3.3333333 digit by digit, you would get 9,9999999. A human with some critical thinking can see it "should" be 1, but a computer that just follows the rules can't. The same applies for binary numbers. Something that looks clean and simple in decimal numbers like 0.2 could be something complicated like 0.00110011001100110011 in binary.

SketchUp handles this quite neatly bu rounding values shown in the UI to a reasonable number of decimal places. Even for internal checks such as if two vertices overlap and should be welded together, SketchUp has some built in thresholds.

**Comment by DanRathbun** [comment]
Besides calculation of numeric literals is a Ruby interpreter function and is not within the purview of the SketchUp API.

(This "Issue" should be closed as a non-API issue.)

----
_REF:_

[Stack Exchange: **Is Floating Point Math Broken?**](https://stackoverflow.com/questions/588004/is-floating-point-math-broken)

**Comment by thomthom** [comment]
This is my go-to reference for floating point behaviour: https://floating-point-gui.de/formats/fp/
