### ISSUE TITLE
Sketchup::get_locale docs issues

### ISSUE THREAD

**Issue by dezmoHU** [SketchUp/api-issue-tracker#681]
[.get_locale](https://ruby.sketchup.com/Sketchup.html#get_locale-class_method)

The documentation is an exact copy of the description of  [.os_language](https://ruby.sketchup.com/Sketchup.html#os_language-class_method). However some words (as well as in the example) need to be changed.

![image](https://user-images.githubusercontent.com/88205452/128504911-36200d5e-db60-4d17-becc-8a91bc1320b2.png)

**Comment by DanRathbun** [comment]
The doc says it is an **alias** for [Sketchup::os_language](https://ruby.sketchup.com/Sketchup.html#os_language-class_method) method.

It is common for Ruby documentation generators to use 1 docstring (which contains parameters, examples, etc.) for all related aliases. Even the Ruby Core docs do this.

----

P.S. - Only instance methods are referred to with a "#" prefix. Class and module methods should use a "::" prefix.

**Comment by dezmoHU** [comment]
> It is common for Ruby documentation generators to use 1 docstring ...

Oh yes. ... But: 
This does not occur e.g. in the  [#length](https://ruby.sketchup.com/Sketchup/Entities.html#length-instance_method).  and [#size](https://ruby.sketchup.com/Sketchup/Entities.html#size-instance_method) 
So somehow it can be "solved", right? 😉 

<sup>(Anyway, it's not a big deal, it's just one of the "oh, this reminded me of..." from other topic, when I was thinking about string comparison based on locale .. 😉)</sup>

**Comment by DanRathbun** [comment]
> So somehow it can be "solved", right?

Yes if the documentation violates the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle.
This can lead to one part getting fixed / corrected, whilst others are forgotten.

**Comment by thomthom** [comment]
The `#length` and `#size` doc comments have duplicated comments because the API used to be inconsistent with offering `size`, `length` and `count`. Some years ago there was an effort to ensure that all containers and enumerable had `size` and `length` as well as `count` doing what it should do for `Enumerable`s.

If we'd only documented `size` or `length` as an alias of itself they'd not each appear as equal in the list of methods. Since these were so common we opted to keep the documentation duplication.

In the case of `Sketchup::get_locale` and `.os_language` I don't think it's worth to make such a duplication. If anything, maybe make one a true alias, but even that effort is dubious at this point compared to all other other work we have.
