### ISSUE TITLE
Method to assign an icon to an Extension for the Extension Manager

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#683]
Currently there is no method to assign an icon to an Extension so that it appears in the Extension Manager (in place of the gray ruby icon)

Could be helpful to easily scroll among the possibly large number of extensions.

**Comment by DanRathbun** [comment]
**This has been discussed in the past.** And there is already an open issue (opened by @Nazz78 in OCT 2017):

[Issue 3: **Feature: `extension.icon`**](https://github.com/SketchUp/api-issue-tracker/issues/3)

_<Echoing my comments below to Issue 3>_

 Currently the icon is being downloaded as a web resource from the EW. It requires that the developer manually upload the icon to their product page.

A method isn't really needed. If a common name were to be finalized and published, developers could just include an image in their RBZ. (Similar to how the RBZ archive contains a "**extension_info.txt**" file that is read by the API's [`SketchupExtension`](https://ruby.sketchup.com/SketchupExtension.html) class.)

> @thomthom  said (NOV 2019) in forum topic "[How do you get a custom icon in the Extension Manager](https://forums.sketchup.com/t/how-do-you-get-a-custom-icon-in-the-extension-manager/108953/3)", post 3:
>
> _We have been talking about adding an interface for extensions to bundle an icon with the extension and have Extension Manager use that._

In the spirit of the existing "**extension_info.txt**" file, I believe that I had proposed filenames using "extension_icon", ie (chosen in this order): "extension_icon.svg" (or "extension_icon.pdf" on Mac), "extension_icon.png", "extension_icon.jpg", "extension_icon.bmp" ... _etc. (Meaning that the [`Sketchup::ExtensionsManager`](https://ruby.sketchup.com/Sketchup/ExtensionsManager.html) chooses the **best** icon available depending upon the need such as display scaling, etc.)

When uploading to the Warehouse (for those extension that publish there) the inclusion of images with the "extension_icon" name **present in the extension subfolder** should take precedence over a manually uploaded icon.

----

But I am **not** opposed to the [`SketchupExtension`](https://ruby.sketchup.com/SketchupExtension.html) class getting a new **`icon`** property so that extensions privately published (or published elsewhere than the EW) can enjoy their icons displaying in the Extension Manager.

An `icon` property for extensions could allow their images to be placed in a nested subfolder rather than the extension's main subfolder **and / or** specify a custom filename. Ie ...
```ruby
ext.icon= File.join(__dir__,"icons/manager_icon")
```
The manager should know what file extension (image type) that is best to use.

**Comment by Fredosixx** [comment]
I close the issue since it is duplicate with issue #3.

Anyway, if the issue #3, opened in October 2017, is still not resolved after almost 4 years, there is little hope than mine would be solved.
