### ISSUE TITLE
Layer folders should not have duplicate names.

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/api-issue-tracker#844]
![image](https://user-images.githubusercontent.com/28385638/201590088-685f4971-890a-4ffe-bca9-2fd7b45828c3.png)

**Comment by thomthom** [comment]
Folder names can have duplicate names per design. On tags has to be unique.

**Comment by DanRathbun** [comment]
Why by design ? It makes no good sense to me why anyone would want duplicate folder names **at the same level**.

Now, I understand that the [`#remove_folder`](https://ruby.sketchup.com/Sketchup/LayerFolder.html#remove_folder-instance_method) method "dumps" all children from the removed folder "up one level", which can also cause duplicates. But why no `#merge_folder` method for the [`LayerFolder`](https://ruby.sketchup.com/Sketchup/LayerFolder.html) and [`Layers`](https://ruby.sketchup.com/Sketchup/Layers.html) classes to easily merge duplicates ?

How does this affect the [`Layers#[]`](https://ruby.sketchup.com/Sketchup/Layers.html#[]-instance_method) method ?

**Comment by LItterBoy-GB** [comment]
It is meaningless to have the same folder name at the same level, which is easy to cause users to find it rather than merge it directly.

**Comment by DanRathbun** [comment]
> But why no `#merge_folder` method for the [`LayerFolder`](https://ruby.sketchup.com/Sketchup/LayerFolder.html) and [`Layers`](https://ruby.sketchup.com/Sketchup/Layers.html) classes to easily merge duplicates ?

Opened new request issue: [845 : Method to Merge Folders for Layers and LayerFolder](https://github.com/SketchUp/api-issue-tracker/issues/845)
