### ISSUE TITLE
UI.Inputbox bugs in SU2023.0.1

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#884]
Two issues with SU2023.1.0 concerning `UI.inputbox`, at least on Windows 10. They have been mentioned on the Sketchup forum, but not sure they were logged to the Issue Database.

**1) Tiny fonts**
Here is the display of the command
```ruby
UI.inputbox(['label'], ['value'], [], 'title')
```
**SU2023.0.1** - Small fonts for label and value
![image](https://user-images.githubusercontent.com/57754157/226283034-5e634d92-d0bf-467d-9568-31a6db88cbba.png)

**SU2022** - The label and value have a normal size
![image](https://user-images.githubusercontent.com/57754157/226283416-f69f6bfa-0435-4475-a225-d819b3b5041c.png)

**2) Input box is modal but does NOT stay in Front when clicking** 

![InputBox SU2023 0 1](https://user-images.githubusercontent.com/57754157/226285583-1bdfa83a-b127-4d5e-92b7-f4ba7be1b306.gif)

**Comment by DanRathbun** [comment]
At least the widths of the edit controls are much better than all throughout SU history.
Also although the size is wrong, the vertical alignment of the text is better in v23.

**Comment by DanRathbun** [comment]
> _Can we consider that an improvement?_

Not really an improvement because I opened an issue that "the rest of SketchUp"'s control and list text sizes are tiny specifically Model Info panels, Preference dialog panels and inspectors text edit controls.

> _The text size should be more consistent with the rest of SketchUp._

Yes they are all consistent, but consistently **too small**.

I even have the general "Make text larger" in Settings set to 125%.

----

Open your Model Info to the Units panel, then run the test inputbox above. You can see that yes the label and text edit control metrics are the same.

I have difficulty reading them of a 25" (63.5 cm) FHD (1920x1080) display at 100% scaling. 
Forget it on the internal 15"FHD display even at 125% scaling.

**Comment by Fredosixx** [comment]
Unless I am wrong, the tiny font has been introduced with SU2023.0.1.

**Comment by DanRathbun** [comment]
> Unless I am wrong, the tiny font has been introduced with SU2023.0.1.

More likely with v23.0.0 or the Qt implementation. (Ie, even the previous abandoned attempt.)

**Yes they are too small.**

----

Also what got too small is the tray and panel caption bar labels. Even when pinned (auto-hidden) into margin tabs.

**Comment by DanRathbun** [comment]
Add, version `23.0.2` to this issue.

**Comment by Fredosixx** [comment]
I don't understand **why the issue is closed**.

The small fonts are still present in SU2024, SU2025 and SU Labs.

![Image](https://github.com/user-attachments/assets/2a460bc7-db84-46bf-960f-8536781bfbd8)

When a problem is closed, please provide the reason and also inform the original poster.
