### ISSUE TITLE
Sketchup::Text does not have a method to set the size and font (unlike the UI)

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#898]
In the UI, you can change the font and size of a text or a model note.

There is NO equivalent method available in the API.

**Comment by DanRathbun** [comment]
## **DUPLICATE**

See **open** issues:

#### Ruby API

* [Issue 47 : Text Labels Properties, Font and Attachment](https://github.com/SketchUp/api-issue-tracker/issues/47)

* [Issue 48 : Dimensions Properties, Font and Attachment](https://github.com/SketchUp/api-issue-tracker/issues/48)

* [Issue 782: (DUPLICATE) Minimal enhancement to create dimensions and texts using ruby](https://github.com/SketchUp/api-issue-tracker/issues/782)

* [Issue 434 : Issue 224 : Need "DimensionsOptions" Sketchup::OptionsProvider instance](https://github.com/SketchUp/api-issue-tracker/issues/224)


#### C API

* [Issue 434 : SUFontCreate() and SUModelAddFont()](https://github.com/SketchUp/api-issue-tracker/issues/434)

**Comment by DanRathbun** [comment]
Also another recent duplicate ... 

* [Issue 887 : Class: Sketchup::Text is any api can change text‘s’letter_height](https://github.com/SketchUp/api-issue-tracker/issues/887) - CLOSED

... in which I noted that this feature has been requested since at least 2008.

So since it hasn't been provided in 15 years, do we assume that the response is: **no** ?

**Comment by Fredosixx** [comment]
OK. Thanks.

I guess we probably need to do without, asyou pointed out...
