### ISSUE TITLE
Messagebox can be obstructed by windows

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/api-issue-tracker#906]
# Bug Reports

1. SketchUp/LayOut Version: Sketchup Pro 2023
2. OS Platform: Windows 11 x64

I clicked the button on the window to pop up a message box, and then clicked on the window again. The window can be moved by clicking on it. This makes it easy for users to not find this message pop-up.

```ruby
dialog = UI::HtmlDialog.new(
  dialog_title: "Dialog Example", preferences_key: nil,
  scrollable: true, resizable: true,
  width: 200, height: 200,
  left: 100, top: 100,
  min_width: 50, min_height: 50,
  max_width: 1000, max_height: 1000,
  style: UI::HtmlDialog::STYLE_DIALOG
)
html = %Q{
<!DOCTYPE html>
<html lang="en">
<body>
<script>
  function f() {
    sketchup.alert('Hello World');
  }
</script>
<button onclick="f()">click</button>
</body>
</html>
}
dialog.add_action_callback('alert') do|_,msg|
  UI.messagebox msg
end
dialog.set_html html
dialog.show
```
![ccc](https://github.com/SketchUp/api-issue-tracker/assets/28385638/7e967df5-2869-46d5-b9d1-919ffe33efb5)

**Comment by Fredosixx** [comment]
This looks like a known problem with SU2023.

Hoep in will be fixed in the next release.

**Comment by DanRathbun** [comment]
Yes, this bug is not limited to [`UI.messagebox`](https://ruby.sketchup.com/UI.html#messagebox-class_method) windows. It affects **all** modal child windows that have been migrated to the Qt GUI framework on Windows.

For example the following issue lists this same bug for [`UI.inputbox`](https://ruby.sketchup.com/UI.html#inputbox-class_method) windows.

* [Issue 884 : UI.Inputbox bugs in SU2023.0.1](https://github.com/SketchUp/api-issue-tracker/issues/884)

The bug also affects [`UI::HtmlDialog`](https://ruby.sketchup.com/UI/HtmlDialog.html) (in slightly different ways) and some native application child windows.
