### ISSUE TITLE
[Request] Layout::SketchUpModel improvements needed

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#910]
The `Layout::SketchUpModel` is probably one central element of the Layout API, since it makes the link between a Sketchup model and the Layout document. After all, users create Layout documents to visualize their Sketchup models.

Surprisingly, the `Layout::SketchUpModel` class is extremely poor...!

1. **There is no way to know which model path the layout viewport corresponds to?** I did not find any method...
2. **The scene identification in the Sketchup model is very weak**. It is based on an _index_, but referring to the Sketchup model at the time the layout document was last updated. Since then, the user may have inserted new scenes, which would defeat the _index_ approach. It would be more useful to **use the scene _persistent_id_ instead of the index**. At least it does not change and is a unique reference.
3. **There is no way to access the camera of the view**, and **no way to change it by program**. Again, a strong restriction.

This somehow defeats the interest of the Layout API. My use cases are all about **controlling and updating a Layout document when a model is changed**. I guess this a standard use case where the Layout API would be the right approach.

With the current limitations of `Layout::SketchUpModel`, this is almost impossible to do anything useful.

**Comment by DanRathbun** [comment]
**First of all, these rant-like complaint topics do not serve the issue tracker well at all.**

Especially when there are already open issues for most of the items in this complaint.

This kind of discussion is **better** held in the API public forum to work out ideas, and then open **specific** requests and bug reports in the tracker that can be acted upon or fixed **individually**.

----

> _1. **There is no way to know which model path the layout viewport corresponds to?** I did not find any method_...

**Already** discussed in open issue ...

* [Issue #324 : **Layout::SketchUpModel#path and #path= methods missing**](https://github.com/SketchUp/api-issue-tracker/issues/324)

> _2\. **The scene identification in the Sketchup model is very weak**. It is based on an _index_, but referring to the Sketchup model at the time the layout document was last updated. Since then, the user may have inserted new scenes, which would defeat the _index_ approach. It would be more useful to **use the scene _persistent_id_ instead of the index**. At least it does not change and is a unique reference_.

I **think** that the index refers to the viewport object's collection of scene pages, not the actual SKP model's scenes collection.

This is because the `"Last saved SketchUp View"` is inserted into the array list at index `0`.

We also can access the viewport's scenes via scene **name** by using the [`Layout::SketchUpModel#scenes`](https://ruby.sketchup.com/Layout/SketchUpModel.html#scenes-instance_method) method. As model scene names must be unique, this then is a foolproof way of asking for the correct scene.
```ruby
# Where viewport is the reference to a Layout::SketchUpModel object ...
scene_name = "Section A-A"
scene_index = viewport.scenes.index(scene_name)
viewport.current_scene= scene_index
```

If you still do not care for this paradigm, please open a **specific** tracker issue to enhance the [`SketchUpModel#current_scene=`](https://ruby.sketchup.com/Layout/SketchUpModel.html#current_scene=-instance_method) method to accept `persistent_id` arguments.

> _3\. **There is no way to access the camera of the view**, and **no way to change it by program**. Again, a strong restriction_.

See Adam's comments in ...
* [Issue #638 : **Layout::SketchUpModel need camera location methods**](https://github.com/SketchUp/api-issue-tracker/issues/638)

> _This somehow defeats the interest of the Layout API. My use cases are all about **controlling and updating a Layout document when a model is changed**_.

Is this done with SketchUp API observers or are `Layout` API observers needed in a live LayOut API scenario?

> _Surprisingly, the `Layout::SketchUpModel` class is extremely poor...!_
> ...
> _With the current limitations of `Layout::SketchUpModel`, this is almost impossible to do anything useful._

* [Issue #566 : **Layout::SketchUpModel class overview needs better description and code example**](https://github.com/SketchUp/api-issue-tracker/issues/566)

* [Issue #325 : **Resizing a Layout::SketchUpModel bounds**](https://github.com/SketchUp/api-issue-tracker/issues/325)

* [Issue #590 : **Layout Ruby API is missing the Update Model Reference feature**](https://github.com/SketchUp/api-issue-tracker/issues/590)

* [Issue #699 : **LayOut API is missing a method to control the SketchUpModel tags/layers**](https://github.com/SketchUp/api-issue-tracker/issues/699)

* [Issue #589 : **Removing and creating new SketchUpModel in Layout Document can cause "Undefined Behavior"**](https://github.com/SketchUp/api-issue-tracker/issues/589)
Speculates that `Layout::Document.remove_entity()` does not remove the internally stored SketchUp Document.
Creating a new `SketchUpModel` entity in the Layout Document uses the cached SketchUp Document instead of the updated one.

**Comment by Fredosixx** [comment]
I think it is also helpful to have global requests formulated as use-cases, instead of atomic requests.

The Trimble developer(s) may come up with a global answer to the use cases, which may be a different apporach that treating each request individually (like the need to have a draw method outside `Sketchup::Tool` gave birt to Overlays.

By the way, I have seen somewhere that the reason that these issues logged about `Layout::SketchUpModel` were not handled is precisely that Trimble wants to revisit profundly the API.

All problems boil down to the fact that it is impossible to re-establish a link between a Layout Document and the SketchUp model(s). This is  serious limitation. You cannot even update a viewport with the `render` method since the layout document does not look t the updated model.

**Comment by thomthom** [comment]
Improvements to the LO API is on our roadmap. This has primarily been a staffing/capacity issue.

Looks like there are issues logged already for everything described? If now, please not individual issues for those as I'll close this as duplicate.
